// Code generated by ent, DO NOT EDIT.

package aichunk

import (
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEQ(FieldTenantID, v))
}

// DocID applies equality check predicate on the "doc_id" field. It's identical to DocIDEQ.
func DocID(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEQ(FieldDocID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEQ(FieldContent, v))
}

// ChunkIndex applies equality check predicate on the "chunk_index" field. It's identical to ChunkIndexEQ.
func ChunkIndex(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEQ(FieldChunkIndex, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.AiChunk {
	return predicate.AiChunk(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNotNull(FieldCreatedAt))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.AiChunk {
	return predicate.AiChunk(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNotNull(FieldTenantID))
}

// DocIDEQ applies the EQ predicate on the "doc_id" field.
func DocIDEQ(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEQ(FieldDocID, v))
}

// DocIDNEQ applies the NEQ predicate on the "doc_id" field.
func DocIDNEQ(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNEQ(FieldDocID, v))
}

// DocIDIn applies the In predicate on the "doc_id" field.
func DocIDIn(vs ...uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldIn(FieldDocID, vs...))
}

// DocIDNotIn applies the NotIn predicate on the "doc_id" field.
func DocIDNotIn(vs ...uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNotIn(FieldDocID, vs...))
}

// DocIDIsNil applies the IsNil predicate on the "doc_id" field.
func DocIDIsNil() predicate.AiChunk {
	return predicate.AiChunk(sql.FieldIsNull(FieldDocID))
}

// DocIDNotNil applies the NotNil predicate on the "doc_id" field.
func DocIDNotNil() predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNotNull(FieldDocID))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.AiChunk {
	return predicate.AiChunk(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldContainsFold(FieldContent, v))
}

// ChunkIndexEQ applies the EQ predicate on the "chunk_index" field.
func ChunkIndexEQ(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldEQ(FieldChunkIndex, v))
}

// ChunkIndexNEQ applies the NEQ predicate on the "chunk_index" field.
func ChunkIndexNEQ(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNEQ(FieldChunkIndex, v))
}

// ChunkIndexIn applies the In predicate on the "chunk_index" field.
func ChunkIndexIn(vs ...uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldIn(FieldChunkIndex, vs...))
}

// ChunkIndexNotIn applies the NotIn predicate on the "chunk_index" field.
func ChunkIndexNotIn(vs ...uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNotIn(FieldChunkIndex, vs...))
}

// ChunkIndexGT applies the GT predicate on the "chunk_index" field.
func ChunkIndexGT(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldGT(FieldChunkIndex, v))
}

// ChunkIndexGTE applies the GTE predicate on the "chunk_index" field.
func ChunkIndexGTE(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldGTE(FieldChunkIndex, v))
}

// ChunkIndexLT applies the LT predicate on the "chunk_index" field.
func ChunkIndexLT(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldLT(FieldChunkIndex, v))
}

// ChunkIndexLTE applies the LTE predicate on the "chunk_index" field.
func ChunkIndexLTE(v uint32) predicate.AiChunk {
	return predicate.AiChunk(sql.FieldLTE(FieldChunkIndex, v))
}

// ChunkIndexIsNil applies the IsNil predicate on the "chunk_index" field.
func ChunkIndexIsNil() predicate.AiChunk {
	return predicate.AiChunk(sql.FieldIsNull(FieldChunkIndex))
}

// ChunkIndexNotNil applies the NotNil predicate on the "chunk_index" field.
func ChunkIndexNotNil() predicate.AiChunk {
	return predicate.AiChunk(sql.FieldNotNull(FieldChunkIndex))
}

// HasDoc applies the HasEdge predicate on the "doc" edge.
func HasDoc() predicate.AiChunk {
	return predicate.AiChunk(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DocTable, DocColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocWith applies the HasEdge predicate on the "doc" edge with a given conditions (other predicates).
func HasDocWith(preds ...predicate.AiDoc) predicate.AiChunk {
	return predicate.AiChunk(func(s *sql.Selector) {
		step := newDocStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AiChunk) predicate.AiChunk {
	return predicate.AiChunk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AiChunk) predicate.AiChunk {
	return predicate.AiChunk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AiChunk) predicate.AiChunk {
	return predicate.AiChunk(sql.NotPredicates(p))
}
