// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/aichunk"
	"go-wind-admin/app/admin/service/internal/data/ent/aidoc"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AI 知识库切片
type AiChunk struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 所属文档ID（edge 外键）
	DocID *uint32 `json:"doc_id,omitempty"`
	// 切片文本
	Content *string `json:"content,omitempty"`
	// 切片序号
	ChunkIndex *uint32 `json:"chunk_index,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AiChunkQuery when eager-loading is set.
	Edges        AiChunkEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AiChunkEdges holds the relations/edges for other nodes in the graph.
type AiChunkEdges struct {
	// Doc holds the value of the doc edge.
	Doc *AiDoc `json:"doc,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DocOrErr returns the Doc value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AiChunkEdges) DocOrErr() (*AiDoc, error) {
	if e.Doc != nil {
		return e.Doc, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aidoc.Label}
	}
	return nil, &NotLoadedError{edge: "doc"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AiChunk) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aichunk.FieldID, aichunk.FieldTenantID, aichunk.FieldDocID, aichunk.FieldChunkIndex:
			values[i] = new(sql.NullInt64)
		case aichunk.FieldContent:
			values[i] = new(sql.NullString)
		case aichunk.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AiChunk fields.
func (_m *AiChunk) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aichunk.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case aichunk.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case aichunk.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case aichunk.FieldDocID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field doc_id", values[i])
			} else if value.Valid {
				_m.DocID = new(uint32)
				*_m.DocID = uint32(value.Int64)
			}
		case aichunk.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = new(string)
				*_m.Content = value.String
			}
		case aichunk.FieldChunkIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chunk_index", values[i])
			} else if value.Valid {
				_m.ChunkIndex = new(uint32)
				*_m.ChunkIndex = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AiChunk.
// This includes values selected through modifiers, order, etc.
func (_m *AiChunk) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDoc queries the "doc" edge of the AiChunk entity.
func (_m *AiChunk) QueryDoc() *AiDocQuery {
	return NewAiChunkClient(_m.config).QueryDoc(_m)
}

// Update returns a builder for updating this AiChunk.
// Note that you need to call AiChunk.Unwrap() before calling this method if this AiChunk
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AiChunk) Update() *AiChunkUpdateOne {
	return NewAiChunkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AiChunk entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AiChunk) Unwrap() *AiChunk {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AiChunk is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AiChunk) String() string {
	var builder strings.Builder
	builder.WriteString("AiChunk(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DocID; v != nil {
		builder.WriteString("doc_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Content; v != nil {
		builder.WriteString("content=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ChunkIndex; v != nil {
		builder.WriteString("chunk_index=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AiChunks is a parsable slice of AiChunk.
type AiChunks []*AiChunk
