// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-wind-admin/app/admin/service/internal/data/ent/aichunk"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AiChunkDelete is the builder for deleting a AiChunk entity.
type AiChunkDelete struct {
	config
	hooks    []Hook
	mutation *AiChunkMutation
}

// Where appends a list predicates to the AiChunkDelete builder.
func (_d *AiChunkDelete) Where(ps ...predicate.AiChunk) *AiChunkDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AiChunkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AiChunkDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AiChunkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(aichunk.Table, sqlgraph.NewFieldSpec(aichunk.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AiChunkDeleteOne is the builder for deleting a single AiChunk entity.
type AiChunkDeleteOne struct {
	_d *AiChunkDelete
}

// Where appends a list predicates to the AiChunkDelete builder.
func (_d *AiChunkDeleteOne) Where(ps ...predicate.AiChunk) *AiChunkDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AiChunkDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{aichunk.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AiChunkDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
