// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-wind-admin/app/admin/service/internal/data/ent/aidoc"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AiDocDelete is the builder for deleting a AiDoc entity.
type AiDocDelete struct {
	config
	hooks    []Hook
	mutation *AiDocMutation
}

// Where appends a list predicates to the AiDocDelete builder.
func (_d *AiDocDelete) Where(ps ...predicate.AiDoc) *AiDocDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AiDocDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AiDocDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AiDocDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(aidoc.Table, sqlgraph.NewFieldSpec(aidoc.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AiDocDeleteOne is the builder for deleting a single AiDoc entity.
type AiDocDeleteOne struct {
	_d *AiDocDelete
}

// Where appends a list predicates to the AiDocDelete builder.
func (_d *AiDocDeleteOne) Where(ps ...predicate.AiDoc) *AiDocDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AiDocDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{aidoc.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AiDocDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
