// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/aidoc"
	"go-wind-admin/app/admin/service/internal/data/ent/aiknowledgebase"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AI 知识库文档
type AiDoc struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 所属知识库ID（edge 外键）
	BaseID *uint32 `json:"base_id,omitempty"`
	// 文档名称
	Name *string `json:"name,omitempty"`
	// 切片数
	ChunkCount *uint32 `json:"chunk_count,omitempty"`
	// 状态：READY/FAILED
	Status *string `json:"status,omitempty"`
	// 失败原因
	ErrorMessage *string `json:"error_message,omitempty"`
	// 上传人用户ID
	UserID *uint32 `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AiDocQuery when eager-loading is set.
	Edges        AiDocEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AiDocEdges holds the relations/edges for other nodes in the graph.
type AiDocEdges struct {
	// Base holds the value of the base edge.
	Base *AiKnowledgeBase `json:"base,omitempty"`
	// Chunks holds the value of the chunks edge.
	Chunks []*AiChunk `json:"chunks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BaseOrErr returns the Base value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AiDocEdges) BaseOrErr() (*AiKnowledgeBase, error) {
	if e.Base != nil {
		return e.Base, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aiknowledgebase.Label}
	}
	return nil, &NotLoadedError{edge: "base"}
}

// ChunksOrErr returns the Chunks value or an error if the edge
// was not loaded in eager-loading.
func (e AiDocEdges) ChunksOrErr() ([]*AiChunk, error) {
	if e.loadedTypes[1] {
		return e.Chunks, nil
	}
	return nil, &NotLoadedError{edge: "chunks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AiDoc) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aidoc.FieldID, aidoc.FieldCreatedBy, aidoc.FieldUpdatedBy, aidoc.FieldDeletedBy, aidoc.FieldTenantID, aidoc.FieldBaseID, aidoc.FieldChunkCount, aidoc.FieldUserID:
			values[i] = new(sql.NullInt64)
		case aidoc.FieldName, aidoc.FieldStatus, aidoc.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case aidoc.FieldCreatedAt, aidoc.FieldUpdatedAt, aidoc.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AiDoc fields.
func (_m *AiDoc) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aidoc.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case aidoc.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case aidoc.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case aidoc.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case aidoc.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case aidoc.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case aidoc.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case aidoc.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case aidoc.FieldBaseID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field base_id", values[i])
			} else if value.Valid {
				_m.BaseID = new(uint32)
				*_m.BaseID = uint32(value.Int64)
			}
		case aidoc.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case aidoc.FieldChunkCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chunk_count", values[i])
			} else if value.Valid {
				_m.ChunkCount = new(uint32)
				*_m.ChunkCount = uint32(value.Int64)
			}
		case aidoc.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = new(string)
				*_m.Status = value.String
			}
		case aidoc.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case aidoc.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(uint32)
				*_m.UserID = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AiDoc.
// This includes values selected through modifiers, order, etc.
func (_m *AiDoc) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBase queries the "base" edge of the AiDoc entity.
func (_m *AiDoc) QueryBase() *AiKnowledgeBaseQuery {
	return NewAiDocClient(_m.config).QueryBase(_m)
}

// QueryChunks queries the "chunks" edge of the AiDoc entity.
func (_m *AiDoc) QueryChunks() *AiChunkQuery {
	return NewAiDocClient(_m.config).QueryChunks(_m)
}

// Update returns a builder for updating this AiDoc.
// Note that you need to call AiDoc.Unwrap() before calling this method if this AiDoc
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AiDoc) Update() *AiDocUpdateOne {
	return NewAiDocClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AiDoc entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AiDoc) Unwrap() *AiDoc {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AiDoc is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AiDoc) String() string {
	var builder strings.Builder
	builder.WriteString("AiDoc(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BaseID; v != nil {
		builder.WriteString("base_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ChunkCount; v != nil {
		builder.WriteString("chunk_count=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Status; v != nil {
		builder.WriteString("status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AiDocs is a parsable slice of AiDoc.
type AiDocs []*AiDoc
