// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/aidoc"
	"go-wind-admin/app/admin/service/internal/data/ent/aiknowledgebase"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AiKnowledgeBaseCreate is the builder for creating a AiKnowledgeBase entity.
type AiKnowledgeBaseCreate struct {
	config
	mutation *AiKnowledgeBaseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AiKnowledgeBaseCreate) SetCreatedAt(v time.Time) *AiKnowledgeBaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AiKnowledgeBaseCreate) SetNillableCreatedAt(v *time.Time) *AiKnowledgeBaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AiKnowledgeBaseCreate) SetUpdatedAt(v time.Time) *AiKnowledgeBaseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AiKnowledgeBaseCreate) SetNillableUpdatedAt(v *time.Time) *AiKnowledgeBaseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AiKnowledgeBaseCreate) SetDeletedAt(v time.Time) *AiKnowledgeBaseCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AiKnowledgeBaseCreate) SetNillableDeletedAt(v *time.Time) *AiKnowledgeBaseCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AiKnowledgeBaseCreate) SetCreatedBy(v uint32) *AiKnowledgeBaseCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *AiKnowledgeBaseCreate) SetNillableCreatedBy(v *uint32) *AiKnowledgeBaseCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *AiKnowledgeBaseCreate) SetUpdatedBy(v uint32) *AiKnowledgeBaseCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *AiKnowledgeBaseCreate) SetNillableUpdatedBy(v *uint32) *AiKnowledgeBaseCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *AiKnowledgeBaseCreate) SetDeletedBy(v uint32) *AiKnowledgeBaseCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *AiKnowledgeBaseCreate) SetNillableDeletedBy(v *uint32) *AiKnowledgeBaseCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *AiKnowledgeBaseCreate) SetTenantID(v uint32) *AiKnowledgeBaseCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *AiKnowledgeBaseCreate) SetNillableTenantID(v *uint32) *AiKnowledgeBaseCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AiKnowledgeBaseCreate) SetName(v string) *AiKnowledgeBaseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *AiKnowledgeBaseCreate) SetNillableName(v *string) *AiKnowledgeBaseCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *AiKnowledgeBaseCreate) SetDescription(v string) *AiKnowledgeBaseCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AiKnowledgeBaseCreate) SetNillableDescription(v *string) *AiKnowledgeBaseCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *AiKnowledgeBaseCreate) SetProviderID(v uint32) *AiKnowledgeBaseCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_c *AiKnowledgeBaseCreate) SetNillableProviderID(v *uint32) *AiKnowledgeBaseCreate {
	if v != nil {
		_c.SetProviderID(*v)
	}
	return _c
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_c *AiKnowledgeBaseCreate) SetEmbeddingModel(v string) *AiKnowledgeBaseCreate {
	_c.mutation.SetEmbeddingModel(v)
	return _c
}

// SetNillableEmbeddingModel sets the "embedding_model" field if the given value is not nil.
func (_c *AiKnowledgeBaseCreate) SetNillableEmbeddingModel(v *string) *AiKnowledgeBaseCreate {
	if v != nil {
		_c.SetEmbeddingModel(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AiKnowledgeBaseCreate) SetUserID(v uint32) *AiKnowledgeBaseCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *AiKnowledgeBaseCreate) SetNillableUserID(v *uint32) *AiKnowledgeBaseCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AiKnowledgeBaseCreate) SetID(v uint32) *AiKnowledgeBaseCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddDocIDs adds the "docs" edge to the AiDoc entity by IDs.
func (_c *AiKnowledgeBaseCreate) AddDocIDs(ids ...uint32) *AiKnowledgeBaseCreate {
	_c.mutation.AddDocIDs(ids...)
	return _c
}

// AddDocs adds the "docs" edges to the AiDoc entity.
func (_c *AiKnowledgeBaseCreate) AddDocs(v ...*AiDoc) *AiKnowledgeBaseCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDocIDs(ids...)
}

// Mutation returns the AiKnowledgeBaseMutation object of the builder.
func (_c *AiKnowledgeBaseCreate) Mutation() *AiKnowledgeBaseMutation {
	return _c.mutation
}

// Save creates the AiKnowledgeBase in the database.
func (_c *AiKnowledgeBaseCreate) Save(ctx context.Context) (*AiKnowledgeBase, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AiKnowledgeBaseCreate) SaveX(ctx context.Context) *AiKnowledgeBase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AiKnowledgeBaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AiKnowledgeBaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AiKnowledgeBaseCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := aiknowledgebase.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AiKnowledgeBaseCreate) check() error {
	if v, ok := _c.mutation.ID(); ok {
		if err := aiknowledgebase.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AiKnowledgeBase.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AiKnowledgeBaseCreate) sqlSave(ctx context.Context) (*AiKnowledgeBase, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AiKnowledgeBaseCreate) createSpec() (*AiKnowledgeBase, *sqlgraph.CreateSpec) {
	var (
		_node = &AiKnowledgeBase{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aiknowledgebase.Table, sqlgraph.NewFieldSpec(aiknowledgebase.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(aiknowledgebase.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(aiknowledgebase.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(aiknowledgebase.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(aiknowledgebase.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(aiknowledgebase.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(aiknowledgebase.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(aiknowledgebase.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(aiknowledgebase.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(aiknowledgebase.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(aiknowledgebase.FieldProviderID, field.TypeUint32, value)
		_node.ProviderID = &value
	}
	if value, ok := _c.mutation.EmbeddingModel(); ok {
		_spec.SetField(aiknowledgebase.FieldEmbeddingModel, field.TypeString, value)
		_node.EmbeddingModel = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(aiknowledgebase.FieldUserID, field.TypeUint32, value)
		_node.UserID = &value
	}
	if nodes := _c.mutation.DocsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aiknowledgebase.DocsTable,
			Columns: []string{aiknowledgebase.DocsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aidoc.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AiKnowledgeBase.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AiKnowledgeBaseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AiKnowledgeBaseCreate) OnConflict(opts ...sql.ConflictOption) *AiKnowledgeBaseUpsertOne {
	_c.conflict = opts
	return &AiKnowledgeBaseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AiKnowledgeBase.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AiKnowledgeBaseCreate) OnConflictColumns(columns ...string) *AiKnowledgeBaseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AiKnowledgeBaseUpsertOne{
		create: _c,
	}
}

type (
	// AiKnowledgeBaseUpsertOne is the builder for "upsert"-ing
	//  one AiKnowledgeBase node.
	AiKnowledgeBaseUpsertOne struct {
		create *AiKnowledgeBaseCreate
	}

	// AiKnowledgeBaseUpsert is the "OnConflict" setter.
	AiKnowledgeBaseUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AiKnowledgeBaseUpsert) SetUpdatedAt(v time.Time) *AiKnowledgeBaseUpsert {
	u.Set(aiknowledgebase.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsert) UpdateUpdatedAt() *AiKnowledgeBaseUpsert {
	u.SetExcluded(aiknowledgebase.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *AiKnowledgeBaseUpsert) ClearUpdatedAt() *AiKnowledgeBaseUpsert {
	u.SetNull(aiknowledgebase.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AiKnowledgeBaseUpsert) SetDeletedAt(v time.Time) *AiKnowledgeBaseUpsert {
	u.Set(aiknowledgebase.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsert) UpdateDeletedAt() *AiKnowledgeBaseUpsert {
	u.SetExcluded(aiknowledgebase.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AiKnowledgeBaseUpsert) ClearDeletedAt() *AiKnowledgeBaseUpsert {
	u.SetNull(aiknowledgebase.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *AiKnowledgeBaseUpsert) SetCreatedBy(v uint32) *AiKnowledgeBaseUpsert {
	u.Set(aiknowledgebase.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsert) UpdateCreatedBy() *AiKnowledgeBaseUpsert {
	u.SetExcluded(aiknowledgebase.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AiKnowledgeBaseUpsert) AddCreatedBy(v uint32) *AiKnowledgeBaseUpsert {
	u.Add(aiknowledgebase.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AiKnowledgeBaseUpsert) ClearCreatedBy() *AiKnowledgeBaseUpsert {
	u.SetNull(aiknowledgebase.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *AiKnowledgeBaseUpsert) SetUpdatedBy(v uint32) *AiKnowledgeBaseUpsert {
	u.Set(aiknowledgebase.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsert) UpdateUpdatedBy() *AiKnowledgeBaseUpsert {
	u.SetExcluded(aiknowledgebase.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *AiKnowledgeBaseUpsert) AddUpdatedBy(v uint32) *AiKnowledgeBaseUpsert {
	u.Add(aiknowledgebase.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *AiKnowledgeBaseUpsert) ClearUpdatedBy() *AiKnowledgeBaseUpsert {
	u.SetNull(aiknowledgebase.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *AiKnowledgeBaseUpsert) SetDeletedBy(v uint32) *AiKnowledgeBaseUpsert {
	u.Set(aiknowledgebase.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsert) UpdateDeletedBy() *AiKnowledgeBaseUpsert {
	u.SetExcluded(aiknowledgebase.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *AiKnowledgeBaseUpsert) AddDeletedBy(v uint32) *AiKnowledgeBaseUpsert {
	u.Add(aiknowledgebase.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *AiKnowledgeBaseUpsert) ClearDeletedBy() *AiKnowledgeBaseUpsert {
	u.SetNull(aiknowledgebase.FieldDeletedBy)
	return u
}

// SetName sets the "name" field.
func (u *AiKnowledgeBaseUpsert) SetName(v string) *AiKnowledgeBaseUpsert {
	u.Set(aiknowledgebase.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsert) UpdateName() *AiKnowledgeBaseUpsert {
	u.SetExcluded(aiknowledgebase.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *AiKnowledgeBaseUpsert) ClearName() *AiKnowledgeBaseUpsert {
	u.SetNull(aiknowledgebase.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *AiKnowledgeBaseUpsert) SetDescription(v string) *AiKnowledgeBaseUpsert {
	u.Set(aiknowledgebase.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsert) UpdateDescription() *AiKnowledgeBaseUpsert {
	u.SetExcluded(aiknowledgebase.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *AiKnowledgeBaseUpsert) ClearDescription() *AiKnowledgeBaseUpsert {
	u.SetNull(aiknowledgebase.FieldDescription)
	return u
}

// SetProviderID sets the "provider_id" field.
func (u *AiKnowledgeBaseUpsert) SetProviderID(v uint32) *AiKnowledgeBaseUpsert {
	u.Set(aiknowledgebase.FieldProviderID, v)
	return u
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsert) UpdateProviderID() *AiKnowledgeBaseUpsert {
	u.SetExcluded(aiknowledgebase.FieldProviderID)
	return u
}

// AddProviderID adds v to the "provider_id" field.
func (u *AiKnowledgeBaseUpsert) AddProviderID(v uint32) *AiKnowledgeBaseUpsert {
	u.Add(aiknowledgebase.FieldProviderID, v)
	return u
}

// ClearProviderID clears the value of the "provider_id" field.
func (u *AiKnowledgeBaseUpsert) ClearProviderID() *AiKnowledgeBaseUpsert {
	u.SetNull(aiknowledgebase.FieldProviderID)
	return u
}

// SetEmbeddingModel sets the "embedding_model" field.
func (u *AiKnowledgeBaseUpsert) SetEmbeddingModel(v string) *AiKnowledgeBaseUpsert {
	u.Set(aiknowledgebase.FieldEmbeddingModel, v)
	return u
}

// UpdateEmbeddingModel sets the "embedding_model" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsert) UpdateEmbeddingModel() *AiKnowledgeBaseUpsert {
	u.SetExcluded(aiknowledgebase.FieldEmbeddingModel)
	return u
}

// ClearEmbeddingModel clears the value of the "embedding_model" field.
func (u *AiKnowledgeBaseUpsert) ClearEmbeddingModel() *AiKnowledgeBaseUpsert {
	u.SetNull(aiknowledgebase.FieldEmbeddingModel)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AiKnowledgeBaseUpsert) SetUserID(v uint32) *AiKnowledgeBaseUpsert {
	u.Set(aiknowledgebase.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsert) UpdateUserID() *AiKnowledgeBaseUpsert {
	u.SetExcluded(aiknowledgebase.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *AiKnowledgeBaseUpsert) AddUserID(v uint32) *AiKnowledgeBaseUpsert {
	u.Add(aiknowledgebase.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *AiKnowledgeBaseUpsert) ClearUserID() *AiKnowledgeBaseUpsert {
	u.SetNull(aiknowledgebase.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AiKnowledgeBase.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(aiknowledgebase.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AiKnowledgeBaseUpsertOne) UpdateNewValues() *AiKnowledgeBaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(aiknowledgebase.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(aiknowledgebase.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(aiknowledgebase.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AiKnowledgeBase.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AiKnowledgeBaseUpsertOne) Ignore() *AiKnowledgeBaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AiKnowledgeBaseUpsertOne) DoNothing() *AiKnowledgeBaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AiKnowledgeBaseCreate.OnConflict
// documentation for more info.
func (u *AiKnowledgeBaseUpsertOne) Update(set func(*AiKnowledgeBaseUpsert)) *AiKnowledgeBaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AiKnowledgeBaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AiKnowledgeBaseUpsertOne) SetUpdatedAt(v time.Time) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertOne) UpdateUpdatedAt() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *AiKnowledgeBaseUpsertOne) ClearUpdatedAt() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AiKnowledgeBaseUpsertOne) SetDeletedAt(v time.Time) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertOne) UpdateDeletedAt() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AiKnowledgeBaseUpsertOne) ClearDeletedAt() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AiKnowledgeBaseUpsertOne) SetCreatedBy(v uint32) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AiKnowledgeBaseUpsertOne) AddCreatedBy(v uint32) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertOne) UpdateCreatedBy() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AiKnowledgeBaseUpsertOne) ClearCreatedBy() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *AiKnowledgeBaseUpsertOne) SetUpdatedBy(v uint32) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *AiKnowledgeBaseUpsertOne) AddUpdatedBy(v uint32) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertOne) UpdateUpdatedBy() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *AiKnowledgeBaseUpsertOne) ClearUpdatedBy() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *AiKnowledgeBaseUpsertOne) SetDeletedBy(v uint32) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *AiKnowledgeBaseUpsertOne) AddDeletedBy(v uint32) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertOne) UpdateDeletedBy() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *AiKnowledgeBaseUpsertOne) ClearDeletedBy() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearDeletedBy()
	})
}

// SetName sets the "name" field.
func (u *AiKnowledgeBaseUpsertOne) SetName(v string) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertOne) UpdateName() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *AiKnowledgeBaseUpsertOne) ClearName() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *AiKnowledgeBaseUpsertOne) SetDescription(v string) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertOne) UpdateDescription() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AiKnowledgeBaseUpsertOne) ClearDescription() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearDescription()
	})
}

// SetProviderID sets the "provider_id" field.
func (u *AiKnowledgeBaseUpsertOne) SetProviderID(v uint32) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetProviderID(v)
	})
}

// AddProviderID adds v to the "provider_id" field.
func (u *AiKnowledgeBaseUpsertOne) AddProviderID(v uint32) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.AddProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertOne) UpdateProviderID() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateProviderID()
	})
}

// ClearProviderID clears the value of the "provider_id" field.
func (u *AiKnowledgeBaseUpsertOne) ClearProviderID() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearProviderID()
	})
}

// SetEmbeddingModel sets the "embedding_model" field.
func (u *AiKnowledgeBaseUpsertOne) SetEmbeddingModel(v string) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetEmbeddingModel(v)
	})
}

// UpdateEmbeddingModel sets the "embedding_model" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertOne) UpdateEmbeddingModel() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateEmbeddingModel()
	})
}

// ClearEmbeddingModel clears the value of the "embedding_model" field.
func (u *AiKnowledgeBaseUpsertOne) ClearEmbeddingModel() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearEmbeddingModel()
	})
}

// SetUserID sets the "user_id" field.
func (u *AiKnowledgeBaseUpsertOne) SetUserID(v uint32) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AiKnowledgeBaseUpsertOne) AddUserID(v uint32) *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertOne) UpdateUserID() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *AiKnowledgeBaseUpsertOne) ClearUserID() *AiKnowledgeBaseUpsertOne {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearUserID()
	})
}

// Exec executes the query.
func (u *AiKnowledgeBaseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AiKnowledgeBaseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AiKnowledgeBaseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AiKnowledgeBaseUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AiKnowledgeBaseUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AiKnowledgeBaseCreateBulk is the builder for creating many AiKnowledgeBase entities in bulk.
type AiKnowledgeBaseCreateBulk struct {
	config
	err      error
	builders []*AiKnowledgeBaseCreate
	conflict []sql.ConflictOption
}

// Save creates the AiKnowledgeBase entities in the database.
func (_c *AiKnowledgeBaseCreateBulk) Save(ctx context.Context) ([]*AiKnowledgeBase, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AiKnowledgeBase, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AiKnowledgeBaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AiKnowledgeBaseCreateBulk) SaveX(ctx context.Context) []*AiKnowledgeBase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AiKnowledgeBaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AiKnowledgeBaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AiKnowledgeBase.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AiKnowledgeBaseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AiKnowledgeBaseCreateBulk) OnConflict(opts ...sql.ConflictOption) *AiKnowledgeBaseUpsertBulk {
	_c.conflict = opts
	return &AiKnowledgeBaseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AiKnowledgeBase.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AiKnowledgeBaseCreateBulk) OnConflictColumns(columns ...string) *AiKnowledgeBaseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AiKnowledgeBaseUpsertBulk{
		create: _c,
	}
}

// AiKnowledgeBaseUpsertBulk is the builder for "upsert"-ing
// a bulk of AiKnowledgeBase nodes.
type AiKnowledgeBaseUpsertBulk struct {
	create *AiKnowledgeBaseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AiKnowledgeBase.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(aiknowledgebase.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AiKnowledgeBaseUpsertBulk) UpdateNewValues() *AiKnowledgeBaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(aiknowledgebase.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(aiknowledgebase.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(aiknowledgebase.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AiKnowledgeBase.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AiKnowledgeBaseUpsertBulk) Ignore() *AiKnowledgeBaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AiKnowledgeBaseUpsertBulk) DoNothing() *AiKnowledgeBaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AiKnowledgeBaseCreateBulk.OnConflict
// documentation for more info.
func (u *AiKnowledgeBaseUpsertBulk) Update(set func(*AiKnowledgeBaseUpsert)) *AiKnowledgeBaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AiKnowledgeBaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AiKnowledgeBaseUpsertBulk) SetUpdatedAt(v time.Time) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertBulk) UpdateUpdatedAt() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *AiKnowledgeBaseUpsertBulk) ClearUpdatedAt() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AiKnowledgeBaseUpsertBulk) SetDeletedAt(v time.Time) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertBulk) UpdateDeletedAt() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AiKnowledgeBaseUpsertBulk) ClearDeletedAt() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AiKnowledgeBaseUpsertBulk) SetCreatedBy(v uint32) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AiKnowledgeBaseUpsertBulk) AddCreatedBy(v uint32) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertBulk) UpdateCreatedBy() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AiKnowledgeBaseUpsertBulk) ClearCreatedBy() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *AiKnowledgeBaseUpsertBulk) SetUpdatedBy(v uint32) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *AiKnowledgeBaseUpsertBulk) AddUpdatedBy(v uint32) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertBulk) UpdateUpdatedBy() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *AiKnowledgeBaseUpsertBulk) ClearUpdatedBy() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *AiKnowledgeBaseUpsertBulk) SetDeletedBy(v uint32) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *AiKnowledgeBaseUpsertBulk) AddDeletedBy(v uint32) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertBulk) UpdateDeletedBy() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *AiKnowledgeBaseUpsertBulk) ClearDeletedBy() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearDeletedBy()
	})
}

// SetName sets the "name" field.
func (u *AiKnowledgeBaseUpsertBulk) SetName(v string) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertBulk) UpdateName() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *AiKnowledgeBaseUpsertBulk) ClearName() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *AiKnowledgeBaseUpsertBulk) SetDescription(v string) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertBulk) UpdateDescription() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AiKnowledgeBaseUpsertBulk) ClearDescription() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearDescription()
	})
}

// SetProviderID sets the "provider_id" field.
func (u *AiKnowledgeBaseUpsertBulk) SetProviderID(v uint32) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetProviderID(v)
	})
}

// AddProviderID adds v to the "provider_id" field.
func (u *AiKnowledgeBaseUpsertBulk) AddProviderID(v uint32) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.AddProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertBulk) UpdateProviderID() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateProviderID()
	})
}

// ClearProviderID clears the value of the "provider_id" field.
func (u *AiKnowledgeBaseUpsertBulk) ClearProviderID() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearProviderID()
	})
}

// SetEmbeddingModel sets the "embedding_model" field.
func (u *AiKnowledgeBaseUpsertBulk) SetEmbeddingModel(v string) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetEmbeddingModel(v)
	})
}

// UpdateEmbeddingModel sets the "embedding_model" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertBulk) UpdateEmbeddingModel() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateEmbeddingModel()
	})
}

// ClearEmbeddingModel clears the value of the "embedding_model" field.
func (u *AiKnowledgeBaseUpsertBulk) ClearEmbeddingModel() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearEmbeddingModel()
	})
}

// SetUserID sets the "user_id" field.
func (u *AiKnowledgeBaseUpsertBulk) SetUserID(v uint32) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AiKnowledgeBaseUpsertBulk) AddUserID(v uint32) *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AiKnowledgeBaseUpsertBulk) UpdateUserID() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *AiKnowledgeBaseUpsertBulk) ClearUserID() *AiKnowledgeBaseUpsertBulk {
	return u.Update(func(s *AiKnowledgeBaseUpsert) {
		s.ClearUserID()
	})
}

// Exec executes the query.
func (u *AiKnowledgeBaseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AiKnowledgeBaseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AiKnowledgeBaseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AiKnowledgeBaseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
