// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/aiprovider"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AiProviderCreate is the builder for creating a AiProvider entity.
type AiProviderCreate struct {
	config
	mutation *AiProviderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AiProviderCreate) SetCreatedAt(v time.Time) *AiProviderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableCreatedAt(v *time.Time) *AiProviderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AiProviderCreate) SetUpdatedAt(v time.Time) *AiProviderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableUpdatedAt(v *time.Time) *AiProviderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AiProviderCreate) SetDeletedAt(v time.Time) *AiProviderCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableDeletedAt(v *time.Time) *AiProviderCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AiProviderCreate) SetCreatedBy(v uint32) *AiProviderCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableCreatedBy(v *uint32) *AiProviderCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *AiProviderCreate) SetUpdatedBy(v uint32) *AiProviderCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableUpdatedBy(v *uint32) *AiProviderCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *AiProviderCreate) SetDeletedBy(v uint32) *AiProviderCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableDeletedBy(v *uint32) *AiProviderCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetIsEnabled sets the "is_enabled" field.
func (_c *AiProviderCreate) SetIsEnabled(v bool) *AiProviderCreate {
	_c.mutation.SetIsEnabled(v)
	return _c
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableIsEnabled(v *bool) *AiProviderCreate {
	if v != nil {
		_c.SetIsEnabled(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AiProviderCreate) SetName(v string) *AiProviderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableName(v *string) *AiProviderCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetModelType sets the "model_type" field.
func (_c *AiProviderCreate) SetModelType(v aiprovider.ModelType) *AiProviderCreate {
	_c.mutation.SetModelType(v)
	return _c
}

// SetNillableModelType sets the "model_type" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableModelType(v *aiprovider.ModelType) *AiProviderCreate {
	if v != nil {
		_c.SetModelType(*v)
	}
	return _c
}

// SetModelName sets the "model_name" field.
func (_c *AiProviderCreate) SetModelName(v string) *AiProviderCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableModelName(v *string) *AiProviderCreate {
	if v != nil {
		_c.SetModelName(*v)
	}
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *AiProviderCreate) SetBaseURL(v string) *AiProviderCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableBaseURL(v *string) *AiProviderCreate {
	if v != nil {
		_c.SetBaseURL(*v)
	}
	return _c
}

// SetOrganization sets the "organization" field.
func (_c *AiProviderCreate) SetOrganization(v string) *AiProviderCreate {
	_c.mutation.SetOrganization(v)
	return _c
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableOrganization(v *string) *AiProviderCreate {
	if v != nil {
		_c.SetOrganization(*v)
	}
	return _c
}

// SetAPIKey sets the "api_key" field.
func (_c *AiProviderCreate) SetAPIKey(v string) *AiProviderCreate {
	_c.mutation.SetAPIKey(v)
	return _c
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableAPIKey(v *string) *AiProviderCreate {
	if v != nil {
		_c.SetAPIKey(*v)
	}
	return _c
}

// SetAPIKeyHint sets the "api_key_hint" field.
func (_c *AiProviderCreate) SetAPIKeyHint(v string) *AiProviderCreate {
	_c.mutation.SetAPIKeyHint(v)
	return _c
}

// SetNillableAPIKeyHint sets the "api_key_hint" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableAPIKeyHint(v *string) *AiProviderCreate {
	if v != nil {
		_c.SetAPIKeyHint(*v)
	}
	return _c
}

// SetLocalHost sets the "local_host" field.
func (_c *AiProviderCreate) SetLocalHost(v string) *AiProviderCreate {
	_c.mutation.SetLocalHost(v)
	return _c
}

// SetNillableLocalHost sets the "local_host" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableLocalHost(v *string) *AiProviderCreate {
	if v != nil {
		_c.SetLocalHost(*v)
	}
	return _c
}

// SetLocalPort sets the "local_port" field.
func (_c *AiProviderCreate) SetLocalPort(v int) *AiProviderCreate {
	_c.mutation.SetLocalPort(v)
	return _c
}

// SetNillableLocalPort sets the "local_port" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableLocalPort(v *int) *AiProviderCreate {
	if v != nil {
		_c.SetLocalPort(*v)
	}
	return _c
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (_c *AiProviderCreate) SetTimeoutSeconds(v int) *AiProviderCreate {
	_c.mutation.SetTimeoutSeconds(v)
	return _c
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableTimeoutSeconds(v *int) *AiProviderCreate {
	if v != nil {
		_c.SetTimeoutSeconds(*v)
	}
	return _c
}

// SetSystemPrompt sets the "system_prompt" field.
func (_c *AiProviderCreate) SetSystemPrompt(v string) *AiProviderCreate {
	_c.mutation.SetSystemPrompt(v)
	return _c
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableSystemPrompt(v *string) *AiProviderCreate {
	if v != nil {
		_c.SetSystemPrompt(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *AiProviderCreate) SetIsDefault(v bool) *AiProviderCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableIsDefault(v *bool) *AiProviderCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *AiProviderCreate) SetRemark(v string) *AiProviderCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *AiProviderCreate) SetNillableRemark(v *string) *AiProviderCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AiProviderCreate) SetID(v uint32) *AiProviderCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AiProviderMutation object of the builder.
func (_c *AiProviderCreate) Mutation() *AiProviderMutation {
	return _c.mutation
}

// Save creates the AiProvider in the database.
func (_c *AiProviderCreate) Save(ctx context.Context) (*AiProvider, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AiProviderCreate) SaveX(ctx context.Context) *AiProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AiProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AiProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AiProviderCreate) defaults() {
	if _, ok := _c.mutation.IsEnabled(); !ok {
		v := aiprovider.DefaultIsEnabled
		_c.mutation.SetIsEnabled(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := aiprovider.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AiProviderCreate) check() error {
	if v, ok := _c.mutation.ModelType(); ok {
		if err := aiprovider.ModelTypeValidator(v); err != nil {
			return &ValidationError{Name: "model_type", err: fmt.Errorf(`ent: validator failed for field "AiProvider.model_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := aiprovider.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AiProvider.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AiProviderCreate) sqlSave(ctx context.Context) (*AiProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AiProviderCreate) createSpec() (*AiProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &AiProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aiprovider.Table, sqlgraph.NewFieldSpec(aiprovider.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(aiprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(aiprovider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(aiprovider.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(aiprovider.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(aiprovider.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(aiprovider.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.IsEnabled(); ok {
		_spec.SetField(aiprovider.FieldIsEnabled, field.TypeBool, value)
		_node.IsEnabled = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(aiprovider.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.ModelType(); ok {
		_spec.SetField(aiprovider.FieldModelType, field.TypeEnum, value)
		_node.ModelType = &value
	}
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(aiprovider.FieldModelName, field.TypeString, value)
		_node.ModelName = &value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(aiprovider.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = &value
	}
	if value, ok := _c.mutation.Organization(); ok {
		_spec.SetField(aiprovider.FieldOrganization, field.TypeString, value)
		_node.Organization = &value
	}
	if value, ok := _c.mutation.APIKey(); ok {
		_spec.SetField(aiprovider.FieldAPIKey, field.TypeString, value)
		_node.APIKey = &value
	}
	if value, ok := _c.mutation.APIKeyHint(); ok {
		_spec.SetField(aiprovider.FieldAPIKeyHint, field.TypeString, value)
		_node.APIKeyHint = &value
	}
	if value, ok := _c.mutation.LocalHost(); ok {
		_spec.SetField(aiprovider.FieldLocalHost, field.TypeString, value)
		_node.LocalHost = &value
	}
	if value, ok := _c.mutation.LocalPort(); ok {
		_spec.SetField(aiprovider.FieldLocalPort, field.TypeInt, value)
		_node.LocalPort = &value
	}
	if value, ok := _c.mutation.TimeoutSeconds(); ok {
		_spec.SetField(aiprovider.FieldTimeoutSeconds, field.TypeInt, value)
		_node.TimeoutSeconds = &value
	}
	if value, ok := _c.mutation.SystemPrompt(); ok {
		_spec.SetField(aiprovider.FieldSystemPrompt, field.TypeString, value)
		_node.SystemPrompt = &value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(aiprovider.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(aiprovider.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AiProvider.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AiProviderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AiProviderCreate) OnConflict(opts ...sql.ConflictOption) *AiProviderUpsertOne {
	_c.conflict = opts
	return &AiProviderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AiProvider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AiProviderCreate) OnConflictColumns(columns ...string) *AiProviderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AiProviderUpsertOne{
		create: _c,
	}
}

type (
	// AiProviderUpsertOne is the builder for "upsert"-ing
	//  one AiProvider node.
	AiProviderUpsertOne struct {
		create *AiProviderCreate
	}

	// AiProviderUpsert is the "OnConflict" setter.
	AiProviderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AiProviderUpsert) SetUpdatedAt(v time.Time) *AiProviderUpsert {
	u.Set(aiprovider.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateUpdatedAt() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *AiProviderUpsert) ClearUpdatedAt() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AiProviderUpsert) SetDeletedAt(v time.Time) *AiProviderUpsert {
	u.Set(aiprovider.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateDeletedAt() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AiProviderUpsert) ClearDeletedAt() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *AiProviderUpsert) SetCreatedBy(v uint32) *AiProviderUpsert {
	u.Set(aiprovider.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateCreatedBy() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AiProviderUpsert) AddCreatedBy(v uint32) *AiProviderUpsert {
	u.Add(aiprovider.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AiProviderUpsert) ClearCreatedBy() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *AiProviderUpsert) SetUpdatedBy(v uint32) *AiProviderUpsert {
	u.Set(aiprovider.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateUpdatedBy() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *AiProviderUpsert) AddUpdatedBy(v uint32) *AiProviderUpsert {
	u.Add(aiprovider.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *AiProviderUpsert) ClearUpdatedBy() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *AiProviderUpsert) SetDeletedBy(v uint32) *AiProviderUpsert {
	u.Set(aiprovider.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateDeletedBy() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *AiProviderUpsert) AddDeletedBy(v uint32) *AiProviderUpsert {
	u.Add(aiprovider.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *AiProviderUpsert) ClearDeletedBy() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldDeletedBy)
	return u
}

// SetIsEnabled sets the "is_enabled" field.
func (u *AiProviderUpsert) SetIsEnabled(v bool) *AiProviderUpsert {
	u.Set(aiprovider.FieldIsEnabled, v)
	return u
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateIsEnabled() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldIsEnabled)
	return u
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (u *AiProviderUpsert) ClearIsEnabled() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldIsEnabled)
	return u
}

// SetName sets the "name" field.
func (u *AiProviderUpsert) SetName(v string) *AiProviderUpsert {
	u.Set(aiprovider.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateName() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *AiProviderUpsert) ClearName() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldName)
	return u
}

// SetModelType sets the "model_type" field.
func (u *AiProviderUpsert) SetModelType(v aiprovider.ModelType) *AiProviderUpsert {
	u.Set(aiprovider.FieldModelType, v)
	return u
}

// UpdateModelType sets the "model_type" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateModelType() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldModelType)
	return u
}

// ClearModelType clears the value of the "model_type" field.
func (u *AiProviderUpsert) ClearModelType() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldModelType)
	return u
}

// SetModelName sets the "model_name" field.
func (u *AiProviderUpsert) SetModelName(v string) *AiProviderUpsert {
	u.Set(aiprovider.FieldModelName, v)
	return u
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateModelName() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldModelName)
	return u
}

// ClearModelName clears the value of the "model_name" field.
func (u *AiProviderUpsert) ClearModelName() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldModelName)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *AiProviderUpsert) SetBaseURL(v string) *AiProviderUpsert {
	u.Set(aiprovider.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateBaseURL() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldBaseURL)
	return u
}

// ClearBaseURL clears the value of the "base_url" field.
func (u *AiProviderUpsert) ClearBaseURL() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldBaseURL)
	return u
}

// SetOrganization sets the "organization" field.
func (u *AiProviderUpsert) SetOrganization(v string) *AiProviderUpsert {
	u.Set(aiprovider.FieldOrganization, v)
	return u
}

// UpdateOrganization sets the "organization" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateOrganization() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldOrganization)
	return u
}

// ClearOrganization clears the value of the "organization" field.
func (u *AiProviderUpsert) ClearOrganization() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldOrganization)
	return u
}

// SetAPIKey sets the "api_key" field.
func (u *AiProviderUpsert) SetAPIKey(v string) *AiProviderUpsert {
	u.Set(aiprovider.FieldAPIKey, v)
	return u
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateAPIKey() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldAPIKey)
	return u
}

// ClearAPIKey clears the value of the "api_key" field.
func (u *AiProviderUpsert) ClearAPIKey() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldAPIKey)
	return u
}

// SetAPIKeyHint sets the "api_key_hint" field.
func (u *AiProviderUpsert) SetAPIKeyHint(v string) *AiProviderUpsert {
	u.Set(aiprovider.FieldAPIKeyHint, v)
	return u
}

// UpdateAPIKeyHint sets the "api_key_hint" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateAPIKeyHint() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldAPIKeyHint)
	return u
}

// ClearAPIKeyHint clears the value of the "api_key_hint" field.
func (u *AiProviderUpsert) ClearAPIKeyHint() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldAPIKeyHint)
	return u
}

// SetLocalHost sets the "local_host" field.
func (u *AiProviderUpsert) SetLocalHost(v string) *AiProviderUpsert {
	u.Set(aiprovider.FieldLocalHost, v)
	return u
}

// UpdateLocalHost sets the "local_host" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateLocalHost() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldLocalHost)
	return u
}

// ClearLocalHost clears the value of the "local_host" field.
func (u *AiProviderUpsert) ClearLocalHost() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldLocalHost)
	return u
}

// SetLocalPort sets the "local_port" field.
func (u *AiProviderUpsert) SetLocalPort(v int) *AiProviderUpsert {
	u.Set(aiprovider.FieldLocalPort, v)
	return u
}

// UpdateLocalPort sets the "local_port" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateLocalPort() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldLocalPort)
	return u
}

// AddLocalPort adds v to the "local_port" field.
func (u *AiProviderUpsert) AddLocalPort(v int) *AiProviderUpsert {
	u.Add(aiprovider.FieldLocalPort, v)
	return u
}

// ClearLocalPort clears the value of the "local_port" field.
func (u *AiProviderUpsert) ClearLocalPort() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldLocalPort)
	return u
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (u *AiProviderUpsert) SetTimeoutSeconds(v int) *AiProviderUpsert {
	u.Set(aiprovider.FieldTimeoutSeconds, v)
	return u
}

// UpdateTimeoutSeconds sets the "timeout_seconds" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateTimeoutSeconds() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldTimeoutSeconds)
	return u
}

// AddTimeoutSeconds adds v to the "timeout_seconds" field.
func (u *AiProviderUpsert) AddTimeoutSeconds(v int) *AiProviderUpsert {
	u.Add(aiprovider.FieldTimeoutSeconds, v)
	return u
}

// ClearTimeoutSeconds clears the value of the "timeout_seconds" field.
func (u *AiProviderUpsert) ClearTimeoutSeconds() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldTimeoutSeconds)
	return u
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *AiProviderUpsert) SetSystemPrompt(v string) *AiProviderUpsert {
	u.Set(aiprovider.FieldSystemPrompt, v)
	return u
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateSystemPrompt() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldSystemPrompt)
	return u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (u *AiProviderUpsert) ClearSystemPrompt() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldSystemPrompt)
	return u
}

// SetIsDefault sets the "is_default" field.
func (u *AiProviderUpsert) SetIsDefault(v bool) *AiProviderUpsert {
	u.Set(aiprovider.FieldIsDefault, v)
	return u
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateIsDefault() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldIsDefault)
	return u
}

// ClearIsDefault clears the value of the "is_default" field.
func (u *AiProviderUpsert) ClearIsDefault() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldIsDefault)
	return u
}

// SetRemark sets the "remark" field.
func (u *AiProviderUpsert) SetRemark(v string) *AiProviderUpsert {
	u.Set(aiprovider.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *AiProviderUpsert) UpdateRemark() *AiProviderUpsert {
	u.SetExcluded(aiprovider.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *AiProviderUpsert) ClearRemark() *AiProviderUpsert {
	u.SetNull(aiprovider.FieldRemark)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AiProvider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(aiprovider.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AiProviderUpsertOne) UpdateNewValues() *AiProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(aiprovider.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(aiprovider.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AiProvider.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AiProviderUpsertOne) Ignore() *AiProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AiProviderUpsertOne) DoNothing() *AiProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AiProviderCreate.OnConflict
// documentation for more info.
func (u *AiProviderUpsertOne) Update(set func(*AiProviderUpsert)) *AiProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AiProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AiProviderUpsertOne) SetUpdatedAt(v time.Time) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateUpdatedAt() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *AiProviderUpsertOne) ClearUpdatedAt() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AiProviderUpsertOne) SetDeletedAt(v time.Time) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateDeletedAt() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AiProviderUpsertOne) ClearDeletedAt() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AiProviderUpsertOne) SetCreatedBy(v uint32) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AiProviderUpsertOne) AddCreatedBy(v uint32) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateCreatedBy() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AiProviderUpsertOne) ClearCreatedBy() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *AiProviderUpsertOne) SetUpdatedBy(v uint32) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *AiProviderUpsertOne) AddUpdatedBy(v uint32) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateUpdatedBy() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *AiProviderUpsertOne) ClearUpdatedBy() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *AiProviderUpsertOne) SetDeletedBy(v uint32) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *AiProviderUpsertOne) AddDeletedBy(v uint32) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateDeletedBy() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *AiProviderUpsertOne) ClearDeletedBy() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearDeletedBy()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *AiProviderUpsertOne) SetIsEnabled(v bool) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateIsEnabled() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateIsEnabled()
	})
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (u *AiProviderUpsertOne) ClearIsEnabled() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearIsEnabled()
	})
}

// SetName sets the "name" field.
func (u *AiProviderUpsertOne) SetName(v string) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateName() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *AiProviderUpsertOne) ClearName() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearName()
	})
}

// SetModelType sets the "model_type" field.
func (u *AiProviderUpsertOne) SetModelType(v aiprovider.ModelType) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetModelType(v)
	})
}

// UpdateModelType sets the "model_type" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateModelType() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateModelType()
	})
}

// ClearModelType clears the value of the "model_type" field.
func (u *AiProviderUpsertOne) ClearModelType() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearModelType()
	})
}

// SetModelName sets the "model_name" field.
func (u *AiProviderUpsertOne) SetModelName(v string) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateModelName() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateModelName()
	})
}

// ClearModelName clears the value of the "model_name" field.
func (u *AiProviderUpsertOne) ClearModelName() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearModelName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *AiProviderUpsertOne) SetBaseURL(v string) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateBaseURL() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateBaseURL()
	})
}

// ClearBaseURL clears the value of the "base_url" field.
func (u *AiProviderUpsertOne) ClearBaseURL() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearBaseURL()
	})
}

// SetOrganization sets the "organization" field.
func (u *AiProviderUpsertOne) SetOrganization(v string) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetOrganization(v)
	})
}

// UpdateOrganization sets the "organization" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateOrganization() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateOrganization()
	})
}

// ClearOrganization clears the value of the "organization" field.
func (u *AiProviderUpsertOne) ClearOrganization() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearOrganization()
	})
}

// SetAPIKey sets the "api_key" field.
func (u *AiProviderUpsertOne) SetAPIKey(v string) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetAPIKey(v)
	})
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateAPIKey() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateAPIKey()
	})
}

// ClearAPIKey clears the value of the "api_key" field.
func (u *AiProviderUpsertOne) ClearAPIKey() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearAPIKey()
	})
}

// SetAPIKeyHint sets the "api_key_hint" field.
func (u *AiProviderUpsertOne) SetAPIKeyHint(v string) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetAPIKeyHint(v)
	})
}

// UpdateAPIKeyHint sets the "api_key_hint" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateAPIKeyHint() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateAPIKeyHint()
	})
}

// ClearAPIKeyHint clears the value of the "api_key_hint" field.
func (u *AiProviderUpsertOne) ClearAPIKeyHint() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearAPIKeyHint()
	})
}

// SetLocalHost sets the "local_host" field.
func (u *AiProviderUpsertOne) SetLocalHost(v string) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetLocalHost(v)
	})
}

// UpdateLocalHost sets the "local_host" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateLocalHost() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateLocalHost()
	})
}

// ClearLocalHost clears the value of the "local_host" field.
func (u *AiProviderUpsertOne) ClearLocalHost() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearLocalHost()
	})
}

// SetLocalPort sets the "local_port" field.
func (u *AiProviderUpsertOne) SetLocalPort(v int) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetLocalPort(v)
	})
}

// AddLocalPort adds v to the "local_port" field.
func (u *AiProviderUpsertOne) AddLocalPort(v int) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.AddLocalPort(v)
	})
}

// UpdateLocalPort sets the "local_port" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateLocalPort() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateLocalPort()
	})
}

// ClearLocalPort clears the value of the "local_port" field.
func (u *AiProviderUpsertOne) ClearLocalPort() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearLocalPort()
	})
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (u *AiProviderUpsertOne) SetTimeoutSeconds(v int) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetTimeoutSeconds(v)
	})
}

// AddTimeoutSeconds adds v to the "timeout_seconds" field.
func (u *AiProviderUpsertOne) AddTimeoutSeconds(v int) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.AddTimeoutSeconds(v)
	})
}

// UpdateTimeoutSeconds sets the "timeout_seconds" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateTimeoutSeconds() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateTimeoutSeconds()
	})
}

// ClearTimeoutSeconds clears the value of the "timeout_seconds" field.
func (u *AiProviderUpsertOne) ClearTimeoutSeconds() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearTimeoutSeconds()
	})
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *AiProviderUpsertOne) SetSystemPrompt(v string) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetSystemPrompt(v)
	})
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateSystemPrompt() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateSystemPrompt()
	})
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (u *AiProviderUpsertOne) ClearSystemPrompt() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearSystemPrompt()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *AiProviderUpsertOne) SetIsDefault(v bool) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateIsDefault() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateIsDefault()
	})
}

// ClearIsDefault clears the value of the "is_default" field.
func (u *AiProviderUpsertOne) ClearIsDefault() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearIsDefault()
	})
}

// SetRemark sets the "remark" field.
func (u *AiProviderUpsertOne) SetRemark(v string) *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *AiProviderUpsertOne) UpdateRemark() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *AiProviderUpsertOne) ClearRemark() *AiProviderUpsertOne {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *AiProviderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AiProviderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AiProviderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AiProviderUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AiProviderUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AiProviderCreateBulk is the builder for creating many AiProvider entities in bulk.
type AiProviderCreateBulk struct {
	config
	err      error
	builders []*AiProviderCreate
	conflict []sql.ConflictOption
}

// Save creates the AiProvider entities in the database.
func (_c *AiProviderCreateBulk) Save(ctx context.Context) ([]*AiProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AiProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AiProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AiProviderCreateBulk) SaveX(ctx context.Context) []*AiProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AiProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AiProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AiProvider.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AiProviderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AiProviderCreateBulk) OnConflict(opts ...sql.ConflictOption) *AiProviderUpsertBulk {
	_c.conflict = opts
	return &AiProviderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AiProvider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AiProviderCreateBulk) OnConflictColumns(columns ...string) *AiProviderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AiProviderUpsertBulk{
		create: _c,
	}
}

// AiProviderUpsertBulk is the builder for "upsert"-ing
// a bulk of AiProvider nodes.
type AiProviderUpsertBulk struct {
	create *AiProviderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AiProvider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(aiprovider.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AiProviderUpsertBulk) UpdateNewValues() *AiProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(aiprovider.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(aiprovider.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AiProvider.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AiProviderUpsertBulk) Ignore() *AiProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AiProviderUpsertBulk) DoNothing() *AiProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AiProviderCreateBulk.OnConflict
// documentation for more info.
func (u *AiProviderUpsertBulk) Update(set func(*AiProviderUpsert)) *AiProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AiProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AiProviderUpsertBulk) SetUpdatedAt(v time.Time) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateUpdatedAt() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *AiProviderUpsertBulk) ClearUpdatedAt() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AiProviderUpsertBulk) SetDeletedAt(v time.Time) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateDeletedAt() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AiProviderUpsertBulk) ClearDeletedAt() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AiProviderUpsertBulk) SetCreatedBy(v uint32) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AiProviderUpsertBulk) AddCreatedBy(v uint32) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateCreatedBy() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *AiProviderUpsertBulk) ClearCreatedBy() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *AiProviderUpsertBulk) SetUpdatedBy(v uint32) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *AiProviderUpsertBulk) AddUpdatedBy(v uint32) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateUpdatedBy() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *AiProviderUpsertBulk) ClearUpdatedBy() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *AiProviderUpsertBulk) SetDeletedBy(v uint32) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *AiProviderUpsertBulk) AddDeletedBy(v uint32) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateDeletedBy() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *AiProviderUpsertBulk) ClearDeletedBy() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearDeletedBy()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *AiProviderUpsertBulk) SetIsEnabled(v bool) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateIsEnabled() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateIsEnabled()
	})
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (u *AiProviderUpsertBulk) ClearIsEnabled() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearIsEnabled()
	})
}

// SetName sets the "name" field.
func (u *AiProviderUpsertBulk) SetName(v string) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateName() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *AiProviderUpsertBulk) ClearName() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearName()
	})
}

// SetModelType sets the "model_type" field.
func (u *AiProviderUpsertBulk) SetModelType(v aiprovider.ModelType) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetModelType(v)
	})
}

// UpdateModelType sets the "model_type" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateModelType() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateModelType()
	})
}

// ClearModelType clears the value of the "model_type" field.
func (u *AiProviderUpsertBulk) ClearModelType() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearModelType()
	})
}

// SetModelName sets the "model_name" field.
func (u *AiProviderUpsertBulk) SetModelName(v string) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateModelName() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateModelName()
	})
}

// ClearModelName clears the value of the "model_name" field.
func (u *AiProviderUpsertBulk) ClearModelName() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearModelName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *AiProviderUpsertBulk) SetBaseURL(v string) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateBaseURL() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateBaseURL()
	})
}

// ClearBaseURL clears the value of the "base_url" field.
func (u *AiProviderUpsertBulk) ClearBaseURL() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearBaseURL()
	})
}

// SetOrganization sets the "organization" field.
func (u *AiProviderUpsertBulk) SetOrganization(v string) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetOrganization(v)
	})
}

// UpdateOrganization sets the "organization" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateOrganization() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateOrganization()
	})
}

// ClearOrganization clears the value of the "organization" field.
func (u *AiProviderUpsertBulk) ClearOrganization() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearOrganization()
	})
}

// SetAPIKey sets the "api_key" field.
func (u *AiProviderUpsertBulk) SetAPIKey(v string) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetAPIKey(v)
	})
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateAPIKey() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateAPIKey()
	})
}

// ClearAPIKey clears the value of the "api_key" field.
func (u *AiProviderUpsertBulk) ClearAPIKey() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearAPIKey()
	})
}

// SetAPIKeyHint sets the "api_key_hint" field.
func (u *AiProviderUpsertBulk) SetAPIKeyHint(v string) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetAPIKeyHint(v)
	})
}

// UpdateAPIKeyHint sets the "api_key_hint" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateAPIKeyHint() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateAPIKeyHint()
	})
}

// ClearAPIKeyHint clears the value of the "api_key_hint" field.
func (u *AiProviderUpsertBulk) ClearAPIKeyHint() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearAPIKeyHint()
	})
}

// SetLocalHost sets the "local_host" field.
func (u *AiProviderUpsertBulk) SetLocalHost(v string) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetLocalHost(v)
	})
}

// UpdateLocalHost sets the "local_host" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateLocalHost() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateLocalHost()
	})
}

// ClearLocalHost clears the value of the "local_host" field.
func (u *AiProviderUpsertBulk) ClearLocalHost() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearLocalHost()
	})
}

// SetLocalPort sets the "local_port" field.
func (u *AiProviderUpsertBulk) SetLocalPort(v int) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetLocalPort(v)
	})
}

// AddLocalPort adds v to the "local_port" field.
func (u *AiProviderUpsertBulk) AddLocalPort(v int) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.AddLocalPort(v)
	})
}

// UpdateLocalPort sets the "local_port" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateLocalPort() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateLocalPort()
	})
}

// ClearLocalPort clears the value of the "local_port" field.
func (u *AiProviderUpsertBulk) ClearLocalPort() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearLocalPort()
	})
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (u *AiProviderUpsertBulk) SetTimeoutSeconds(v int) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetTimeoutSeconds(v)
	})
}

// AddTimeoutSeconds adds v to the "timeout_seconds" field.
func (u *AiProviderUpsertBulk) AddTimeoutSeconds(v int) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.AddTimeoutSeconds(v)
	})
}

// UpdateTimeoutSeconds sets the "timeout_seconds" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateTimeoutSeconds() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateTimeoutSeconds()
	})
}

// ClearTimeoutSeconds clears the value of the "timeout_seconds" field.
func (u *AiProviderUpsertBulk) ClearTimeoutSeconds() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearTimeoutSeconds()
	})
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *AiProviderUpsertBulk) SetSystemPrompt(v string) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetSystemPrompt(v)
	})
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateSystemPrompt() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateSystemPrompt()
	})
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (u *AiProviderUpsertBulk) ClearSystemPrompt() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearSystemPrompt()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *AiProviderUpsertBulk) SetIsDefault(v bool) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateIsDefault() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateIsDefault()
	})
}

// ClearIsDefault clears the value of the "is_default" field.
func (u *AiProviderUpsertBulk) ClearIsDefault() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearIsDefault()
	})
}

// SetRemark sets the "remark" field.
func (u *AiProviderUpsertBulk) SetRemark(v string) *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *AiProviderUpsertBulk) UpdateRemark() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *AiProviderUpsertBulk) ClearRemark() *AiProviderUpsertBulk {
	return u.Update(func(s *AiProviderUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *AiProviderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AiProviderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AiProviderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AiProviderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
