// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/aiprovider"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AiProviderUpdate is the builder for updating AiProvider entities.
type AiProviderUpdate struct {
	config
	hooks     []Hook
	mutation  *AiProviderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AiProviderUpdate builder.
func (_u *AiProviderUpdate) Where(ps ...predicate.AiProvider) *AiProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AiProviderUpdate) SetUpdatedAt(v time.Time) *AiProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableUpdatedAt(v *time.Time) *AiProviderUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *AiProviderUpdate) ClearUpdatedAt() *AiProviderUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AiProviderUpdate) SetDeletedAt(v time.Time) *AiProviderUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableDeletedAt(v *time.Time) *AiProviderUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AiProviderUpdate) ClearDeletedAt() *AiProviderUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AiProviderUpdate) SetCreatedBy(v uint32) *AiProviderUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableCreatedBy(v *uint32) *AiProviderUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *AiProviderUpdate) AddCreatedBy(v int32) *AiProviderUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AiProviderUpdate) ClearCreatedBy() *AiProviderUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AiProviderUpdate) SetUpdatedBy(v uint32) *AiProviderUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableUpdatedBy(v *uint32) *AiProviderUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *AiProviderUpdate) AddUpdatedBy(v int32) *AiProviderUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *AiProviderUpdate) ClearUpdatedBy() *AiProviderUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *AiProviderUpdate) SetDeletedBy(v uint32) *AiProviderUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableDeletedBy(v *uint32) *AiProviderUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *AiProviderUpdate) AddDeletedBy(v int32) *AiProviderUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *AiProviderUpdate) ClearDeletedBy() *AiProviderUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *AiProviderUpdate) SetIsEnabled(v bool) *AiProviderUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableIsEnabled(v *bool) *AiProviderUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (_u *AiProviderUpdate) ClearIsEnabled() *AiProviderUpdate {
	_u.mutation.ClearIsEnabled()
	return _u
}

// SetName sets the "name" field.
func (_u *AiProviderUpdate) SetName(v string) *AiProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableName(v *string) *AiProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *AiProviderUpdate) ClearName() *AiProviderUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetModelType sets the "model_type" field.
func (_u *AiProviderUpdate) SetModelType(v aiprovider.ModelType) *AiProviderUpdate {
	_u.mutation.SetModelType(v)
	return _u
}

// SetNillableModelType sets the "model_type" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableModelType(v *aiprovider.ModelType) *AiProviderUpdate {
	if v != nil {
		_u.SetModelType(*v)
	}
	return _u
}

// ClearModelType clears the value of the "model_type" field.
func (_u *AiProviderUpdate) ClearModelType() *AiProviderUpdate {
	_u.mutation.ClearModelType()
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *AiProviderUpdate) SetModelName(v string) *AiProviderUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableModelName(v *string) *AiProviderUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// ClearModelName clears the value of the "model_name" field.
func (_u *AiProviderUpdate) ClearModelName() *AiProviderUpdate {
	_u.mutation.ClearModelName()
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *AiProviderUpdate) SetBaseURL(v string) *AiProviderUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableBaseURL(v *string) *AiProviderUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// ClearBaseURL clears the value of the "base_url" field.
func (_u *AiProviderUpdate) ClearBaseURL() *AiProviderUpdate {
	_u.mutation.ClearBaseURL()
	return _u
}

// SetOrganization sets the "organization" field.
func (_u *AiProviderUpdate) SetOrganization(v string) *AiProviderUpdate {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableOrganization(v *string) *AiProviderUpdate {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// ClearOrganization clears the value of the "organization" field.
func (_u *AiProviderUpdate) ClearOrganization() *AiProviderUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *AiProviderUpdate) SetAPIKey(v string) *AiProviderUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableAPIKey(v *string) *AiProviderUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// ClearAPIKey clears the value of the "api_key" field.
func (_u *AiProviderUpdate) ClearAPIKey() *AiProviderUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// SetAPIKeyHint sets the "api_key_hint" field.
func (_u *AiProviderUpdate) SetAPIKeyHint(v string) *AiProviderUpdate {
	_u.mutation.SetAPIKeyHint(v)
	return _u
}

// SetNillableAPIKeyHint sets the "api_key_hint" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableAPIKeyHint(v *string) *AiProviderUpdate {
	if v != nil {
		_u.SetAPIKeyHint(*v)
	}
	return _u
}

// ClearAPIKeyHint clears the value of the "api_key_hint" field.
func (_u *AiProviderUpdate) ClearAPIKeyHint() *AiProviderUpdate {
	_u.mutation.ClearAPIKeyHint()
	return _u
}

// SetLocalHost sets the "local_host" field.
func (_u *AiProviderUpdate) SetLocalHost(v string) *AiProviderUpdate {
	_u.mutation.SetLocalHost(v)
	return _u
}

// SetNillableLocalHost sets the "local_host" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableLocalHost(v *string) *AiProviderUpdate {
	if v != nil {
		_u.SetLocalHost(*v)
	}
	return _u
}

// ClearLocalHost clears the value of the "local_host" field.
func (_u *AiProviderUpdate) ClearLocalHost() *AiProviderUpdate {
	_u.mutation.ClearLocalHost()
	return _u
}

// SetLocalPort sets the "local_port" field.
func (_u *AiProviderUpdate) SetLocalPort(v int) *AiProviderUpdate {
	_u.mutation.ResetLocalPort()
	_u.mutation.SetLocalPort(v)
	return _u
}

// SetNillableLocalPort sets the "local_port" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableLocalPort(v *int) *AiProviderUpdate {
	if v != nil {
		_u.SetLocalPort(*v)
	}
	return _u
}

// AddLocalPort adds value to the "local_port" field.
func (_u *AiProviderUpdate) AddLocalPort(v int) *AiProviderUpdate {
	_u.mutation.AddLocalPort(v)
	return _u
}

// ClearLocalPort clears the value of the "local_port" field.
func (_u *AiProviderUpdate) ClearLocalPort() *AiProviderUpdate {
	_u.mutation.ClearLocalPort()
	return _u
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (_u *AiProviderUpdate) SetTimeoutSeconds(v int) *AiProviderUpdate {
	_u.mutation.ResetTimeoutSeconds()
	_u.mutation.SetTimeoutSeconds(v)
	return _u
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableTimeoutSeconds(v *int) *AiProviderUpdate {
	if v != nil {
		_u.SetTimeoutSeconds(*v)
	}
	return _u
}

// AddTimeoutSeconds adds value to the "timeout_seconds" field.
func (_u *AiProviderUpdate) AddTimeoutSeconds(v int) *AiProviderUpdate {
	_u.mutation.AddTimeoutSeconds(v)
	return _u
}

// ClearTimeoutSeconds clears the value of the "timeout_seconds" field.
func (_u *AiProviderUpdate) ClearTimeoutSeconds() *AiProviderUpdate {
	_u.mutation.ClearTimeoutSeconds()
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *AiProviderUpdate) SetSystemPrompt(v string) *AiProviderUpdate {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableSystemPrompt(v *string) *AiProviderUpdate {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *AiProviderUpdate) ClearSystemPrompt() *AiProviderUpdate {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *AiProviderUpdate) SetIsDefault(v bool) *AiProviderUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableIsDefault(v *bool) *AiProviderUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// ClearIsDefault clears the value of the "is_default" field.
func (_u *AiProviderUpdate) ClearIsDefault() *AiProviderUpdate {
	_u.mutation.ClearIsDefault()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *AiProviderUpdate) SetRemark(v string) *AiProviderUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *AiProviderUpdate) SetNillableRemark(v *string) *AiProviderUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *AiProviderUpdate) ClearRemark() *AiProviderUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// Mutation returns the AiProviderMutation object of the builder.
func (_u *AiProviderUpdate) Mutation() *AiProviderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AiProviderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AiProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AiProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AiProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AiProviderUpdate) check() error {
	if v, ok := _u.mutation.ModelType(); ok {
		if err := aiprovider.ModelTypeValidator(v); err != nil {
			return &ValidationError{Name: "model_type", err: fmt.Errorf(`ent: validator failed for field "AiProvider.model_type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AiProviderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AiProviderUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AiProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aiprovider.Table, aiprovider.Columns, sqlgraph.NewFieldSpec(aiprovider.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(aiprovider.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aiprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(aiprovider.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(aiprovider.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(aiprovider.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(aiprovider.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(aiprovider.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(aiprovider.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(aiprovider.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(aiprovider.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(aiprovider.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(aiprovider.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(aiprovider.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(aiprovider.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(aiprovider.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.IsEnabledCleared() {
		_spec.ClearField(aiprovider.FieldIsEnabled, field.TypeBool)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(aiprovider.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(aiprovider.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.ModelType(); ok {
		_spec.SetField(aiprovider.FieldModelType, field.TypeEnum, value)
	}
	if _u.mutation.ModelTypeCleared() {
		_spec.ClearField(aiprovider.FieldModelType, field.TypeEnum)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(aiprovider.FieldModelName, field.TypeString, value)
	}
	if _u.mutation.ModelNameCleared() {
		_spec.ClearField(aiprovider.FieldModelName, field.TypeString)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(aiprovider.FieldBaseURL, field.TypeString, value)
	}
	if _u.mutation.BaseURLCleared() {
		_spec.ClearField(aiprovider.FieldBaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(aiprovider.FieldOrganization, field.TypeString, value)
	}
	if _u.mutation.OrganizationCleared() {
		_spec.ClearField(aiprovider.FieldOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(aiprovider.FieldAPIKey, field.TypeString, value)
	}
	if _u.mutation.APIKeyCleared() {
		_spec.ClearField(aiprovider.FieldAPIKey, field.TypeString)
	}
	if value, ok := _u.mutation.APIKeyHint(); ok {
		_spec.SetField(aiprovider.FieldAPIKeyHint, field.TypeString, value)
	}
	if _u.mutation.APIKeyHintCleared() {
		_spec.ClearField(aiprovider.FieldAPIKeyHint, field.TypeString)
	}
	if value, ok := _u.mutation.LocalHost(); ok {
		_spec.SetField(aiprovider.FieldLocalHost, field.TypeString, value)
	}
	if _u.mutation.LocalHostCleared() {
		_spec.ClearField(aiprovider.FieldLocalHost, field.TypeString)
	}
	if value, ok := _u.mutation.LocalPort(); ok {
		_spec.SetField(aiprovider.FieldLocalPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLocalPort(); ok {
		_spec.AddField(aiprovider.FieldLocalPort, field.TypeInt, value)
	}
	if _u.mutation.LocalPortCleared() {
		_spec.ClearField(aiprovider.FieldLocalPort, field.TypeInt)
	}
	if value, ok := _u.mutation.TimeoutSeconds(); ok {
		_spec.SetField(aiprovider.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutSeconds(); ok {
		_spec.AddField(aiprovider.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if _u.mutation.TimeoutSecondsCleared() {
		_spec.ClearField(aiprovider.FieldTimeoutSeconds, field.TypeInt)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(aiprovider.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(aiprovider.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(aiprovider.FieldIsDefault, field.TypeBool, value)
	}
	if _u.mutation.IsDefaultCleared() {
		_spec.ClearField(aiprovider.FieldIsDefault, field.TypeBool)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(aiprovider.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(aiprovider.FieldRemark, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AiProviderUpdateOne is the builder for updating a single AiProvider entity.
type AiProviderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AiProviderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AiProviderUpdateOne) SetUpdatedAt(v time.Time) *AiProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableUpdatedAt(v *time.Time) *AiProviderUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *AiProviderUpdateOne) ClearUpdatedAt() *AiProviderUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AiProviderUpdateOne) SetDeletedAt(v time.Time) *AiProviderUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableDeletedAt(v *time.Time) *AiProviderUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AiProviderUpdateOne) ClearDeletedAt() *AiProviderUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AiProviderUpdateOne) SetCreatedBy(v uint32) *AiProviderUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableCreatedBy(v *uint32) *AiProviderUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *AiProviderUpdateOne) AddCreatedBy(v int32) *AiProviderUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AiProviderUpdateOne) ClearCreatedBy() *AiProviderUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AiProviderUpdateOne) SetUpdatedBy(v uint32) *AiProviderUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableUpdatedBy(v *uint32) *AiProviderUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *AiProviderUpdateOne) AddUpdatedBy(v int32) *AiProviderUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *AiProviderUpdateOne) ClearUpdatedBy() *AiProviderUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *AiProviderUpdateOne) SetDeletedBy(v uint32) *AiProviderUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableDeletedBy(v *uint32) *AiProviderUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *AiProviderUpdateOne) AddDeletedBy(v int32) *AiProviderUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *AiProviderUpdateOne) ClearDeletedBy() *AiProviderUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *AiProviderUpdateOne) SetIsEnabled(v bool) *AiProviderUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableIsEnabled(v *bool) *AiProviderUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (_u *AiProviderUpdateOne) ClearIsEnabled() *AiProviderUpdateOne {
	_u.mutation.ClearIsEnabled()
	return _u
}

// SetName sets the "name" field.
func (_u *AiProviderUpdateOne) SetName(v string) *AiProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableName(v *string) *AiProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *AiProviderUpdateOne) ClearName() *AiProviderUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetModelType sets the "model_type" field.
func (_u *AiProviderUpdateOne) SetModelType(v aiprovider.ModelType) *AiProviderUpdateOne {
	_u.mutation.SetModelType(v)
	return _u
}

// SetNillableModelType sets the "model_type" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableModelType(v *aiprovider.ModelType) *AiProviderUpdateOne {
	if v != nil {
		_u.SetModelType(*v)
	}
	return _u
}

// ClearModelType clears the value of the "model_type" field.
func (_u *AiProviderUpdateOne) ClearModelType() *AiProviderUpdateOne {
	_u.mutation.ClearModelType()
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *AiProviderUpdateOne) SetModelName(v string) *AiProviderUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableModelName(v *string) *AiProviderUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// ClearModelName clears the value of the "model_name" field.
func (_u *AiProviderUpdateOne) ClearModelName() *AiProviderUpdateOne {
	_u.mutation.ClearModelName()
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *AiProviderUpdateOne) SetBaseURL(v string) *AiProviderUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableBaseURL(v *string) *AiProviderUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// ClearBaseURL clears the value of the "base_url" field.
func (_u *AiProviderUpdateOne) ClearBaseURL() *AiProviderUpdateOne {
	_u.mutation.ClearBaseURL()
	return _u
}

// SetOrganization sets the "organization" field.
func (_u *AiProviderUpdateOne) SetOrganization(v string) *AiProviderUpdateOne {
	_u.mutation.SetOrganization(v)
	return _u
}

// SetNillableOrganization sets the "organization" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableOrganization(v *string) *AiProviderUpdateOne {
	if v != nil {
		_u.SetOrganization(*v)
	}
	return _u
}

// ClearOrganization clears the value of the "organization" field.
func (_u *AiProviderUpdateOne) ClearOrganization() *AiProviderUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *AiProviderUpdateOne) SetAPIKey(v string) *AiProviderUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableAPIKey(v *string) *AiProviderUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// ClearAPIKey clears the value of the "api_key" field.
func (_u *AiProviderUpdateOne) ClearAPIKey() *AiProviderUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// SetAPIKeyHint sets the "api_key_hint" field.
func (_u *AiProviderUpdateOne) SetAPIKeyHint(v string) *AiProviderUpdateOne {
	_u.mutation.SetAPIKeyHint(v)
	return _u
}

// SetNillableAPIKeyHint sets the "api_key_hint" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableAPIKeyHint(v *string) *AiProviderUpdateOne {
	if v != nil {
		_u.SetAPIKeyHint(*v)
	}
	return _u
}

// ClearAPIKeyHint clears the value of the "api_key_hint" field.
func (_u *AiProviderUpdateOne) ClearAPIKeyHint() *AiProviderUpdateOne {
	_u.mutation.ClearAPIKeyHint()
	return _u
}

// SetLocalHost sets the "local_host" field.
func (_u *AiProviderUpdateOne) SetLocalHost(v string) *AiProviderUpdateOne {
	_u.mutation.SetLocalHost(v)
	return _u
}

// SetNillableLocalHost sets the "local_host" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableLocalHost(v *string) *AiProviderUpdateOne {
	if v != nil {
		_u.SetLocalHost(*v)
	}
	return _u
}

// ClearLocalHost clears the value of the "local_host" field.
func (_u *AiProviderUpdateOne) ClearLocalHost() *AiProviderUpdateOne {
	_u.mutation.ClearLocalHost()
	return _u
}

// SetLocalPort sets the "local_port" field.
func (_u *AiProviderUpdateOne) SetLocalPort(v int) *AiProviderUpdateOne {
	_u.mutation.ResetLocalPort()
	_u.mutation.SetLocalPort(v)
	return _u
}

// SetNillableLocalPort sets the "local_port" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableLocalPort(v *int) *AiProviderUpdateOne {
	if v != nil {
		_u.SetLocalPort(*v)
	}
	return _u
}

// AddLocalPort adds value to the "local_port" field.
func (_u *AiProviderUpdateOne) AddLocalPort(v int) *AiProviderUpdateOne {
	_u.mutation.AddLocalPort(v)
	return _u
}

// ClearLocalPort clears the value of the "local_port" field.
func (_u *AiProviderUpdateOne) ClearLocalPort() *AiProviderUpdateOne {
	_u.mutation.ClearLocalPort()
	return _u
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (_u *AiProviderUpdateOne) SetTimeoutSeconds(v int) *AiProviderUpdateOne {
	_u.mutation.ResetTimeoutSeconds()
	_u.mutation.SetTimeoutSeconds(v)
	return _u
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableTimeoutSeconds(v *int) *AiProviderUpdateOne {
	if v != nil {
		_u.SetTimeoutSeconds(*v)
	}
	return _u
}

// AddTimeoutSeconds adds value to the "timeout_seconds" field.
func (_u *AiProviderUpdateOne) AddTimeoutSeconds(v int) *AiProviderUpdateOne {
	_u.mutation.AddTimeoutSeconds(v)
	return _u
}

// ClearTimeoutSeconds clears the value of the "timeout_seconds" field.
func (_u *AiProviderUpdateOne) ClearTimeoutSeconds() *AiProviderUpdateOne {
	_u.mutation.ClearTimeoutSeconds()
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *AiProviderUpdateOne) SetSystemPrompt(v string) *AiProviderUpdateOne {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableSystemPrompt(v *string) *AiProviderUpdateOne {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *AiProviderUpdateOne) ClearSystemPrompt() *AiProviderUpdateOne {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *AiProviderUpdateOne) SetIsDefault(v bool) *AiProviderUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableIsDefault(v *bool) *AiProviderUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// ClearIsDefault clears the value of the "is_default" field.
func (_u *AiProviderUpdateOne) ClearIsDefault() *AiProviderUpdateOne {
	_u.mutation.ClearIsDefault()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *AiProviderUpdateOne) SetRemark(v string) *AiProviderUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *AiProviderUpdateOne) SetNillableRemark(v *string) *AiProviderUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *AiProviderUpdateOne) ClearRemark() *AiProviderUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// Mutation returns the AiProviderMutation object of the builder.
func (_u *AiProviderUpdateOne) Mutation() *AiProviderMutation {
	return _u.mutation
}

// Where appends a list predicates to the AiProviderUpdate builder.
func (_u *AiProviderUpdateOne) Where(ps ...predicate.AiProvider) *AiProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AiProviderUpdateOne) Select(field string, fields ...string) *AiProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AiProvider entity.
func (_u *AiProviderUpdateOne) Save(ctx context.Context) (*AiProvider, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AiProviderUpdateOne) SaveX(ctx context.Context) *AiProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AiProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AiProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AiProviderUpdateOne) check() error {
	if v, ok := _u.mutation.ModelType(); ok {
		if err := aiprovider.ModelTypeValidator(v); err != nil {
			return &ValidationError{Name: "model_type", err: fmt.Errorf(`ent: validator failed for field "AiProvider.model_type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AiProviderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AiProviderUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AiProviderUpdateOne) sqlSave(ctx context.Context) (_node *AiProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aiprovider.Table, aiprovider.Columns, sqlgraph.NewFieldSpec(aiprovider.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AiProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aiprovider.FieldID)
		for _, f := range fields {
			if !aiprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aiprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(aiprovider.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aiprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(aiprovider.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(aiprovider.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(aiprovider.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(aiprovider.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(aiprovider.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(aiprovider.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(aiprovider.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(aiprovider.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(aiprovider.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(aiprovider.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(aiprovider.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(aiprovider.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(aiprovider.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.IsEnabledCleared() {
		_spec.ClearField(aiprovider.FieldIsEnabled, field.TypeBool)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(aiprovider.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(aiprovider.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.ModelType(); ok {
		_spec.SetField(aiprovider.FieldModelType, field.TypeEnum, value)
	}
	if _u.mutation.ModelTypeCleared() {
		_spec.ClearField(aiprovider.FieldModelType, field.TypeEnum)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(aiprovider.FieldModelName, field.TypeString, value)
	}
	if _u.mutation.ModelNameCleared() {
		_spec.ClearField(aiprovider.FieldModelName, field.TypeString)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(aiprovider.FieldBaseURL, field.TypeString, value)
	}
	if _u.mutation.BaseURLCleared() {
		_spec.ClearField(aiprovider.FieldBaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.Organization(); ok {
		_spec.SetField(aiprovider.FieldOrganization, field.TypeString, value)
	}
	if _u.mutation.OrganizationCleared() {
		_spec.ClearField(aiprovider.FieldOrganization, field.TypeString)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(aiprovider.FieldAPIKey, field.TypeString, value)
	}
	if _u.mutation.APIKeyCleared() {
		_spec.ClearField(aiprovider.FieldAPIKey, field.TypeString)
	}
	if value, ok := _u.mutation.APIKeyHint(); ok {
		_spec.SetField(aiprovider.FieldAPIKeyHint, field.TypeString, value)
	}
	if _u.mutation.APIKeyHintCleared() {
		_spec.ClearField(aiprovider.FieldAPIKeyHint, field.TypeString)
	}
	if value, ok := _u.mutation.LocalHost(); ok {
		_spec.SetField(aiprovider.FieldLocalHost, field.TypeString, value)
	}
	if _u.mutation.LocalHostCleared() {
		_spec.ClearField(aiprovider.FieldLocalHost, field.TypeString)
	}
	if value, ok := _u.mutation.LocalPort(); ok {
		_spec.SetField(aiprovider.FieldLocalPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLocalPort(); ok {
		_spec.AddField(aiprovider.FieldLocalPort, field.TypeInt, value)
	}
	if _u.mutation.LocalPortCleared() {
		_spec.ClearField(aiprovider.FieldLocalPort, field.TypeInt)
	}
	if value, ok := _u.mutation.TimeoutSeconds(); ok {
		_spec.SetField(aiprovider.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutSeconds(); ok {
		_spec.AddField(aiprovider.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if _u.mutation.TimeoutSecondsCleared() {
		_spec.ClearField(aiprovider.FieldTimeoutSeconds, field.TypeInt)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(aiprovider.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(aiprovider.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(aiprovider.FieldIsDefault, field.TypeBool, value)
	}
	if _u.mutation.IsDefaultCleared() {
		_spec.ClearField(aiprovider.FieldIsDefault, field.TypeBool)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(aiprovider.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(aiprovider.FieldRemark, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &AiProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
