// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/aiusagelog"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AiUsageLogUpdate is the builder for updating AiUsageLog entities.
type AiUsageLogUpdate struct {
	config
	hooks     []Hook
	mutation  *AiUsageLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AiUsageLogUpdate builder.
func (_u *AiUsageLogUpdate) Where(ps ...predicate.AiUsageLog) *AiUsageLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *AiUsageLogUpdate) SetProviderID(v uint32) *AiUsageLogUpdate {
	_u.mutation.ResetProviderID()
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *AiUsageLogUpdate) SetNillableProviderID(v *uint32) *AiUsageLogUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// AddProviderID adds value to the "provider_id" field.
func (_u *AiUsageLogUpdate) AddProviderID(v int32) *AiUsageLogUpdate {
	_u.mutation.AddProviderID(v)
	return _u
}

// ClearProviderID clears the value of the "provider_id" field.
func (_u *AiUsageLogUpdate) ClearProviderID() *AiUsageLogUpdate {
	_u.mutation.ClearProviderID()
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *AiUsageLogUpdate) SetConversationID(v uint32) *AiUsageLogUpdate {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *AiUsageLogUpdate) SetNillableConversationID(v *uint32) *AiUsageLogUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *AiUsageLogUpdate) AddConversationID(v int32) *AiUsageLogUpdate {
	_u.mutation.AddConversationID(v)
	return _u
}

// ClearConversationID clears the value of the "conversation_id" field.
func (_u *AiUsageLogUpdate) ClearConversationID() *AiUsageLogUpdate {
	_u.mutation.ClearConversationID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AiUsageLogUpdate) SetUserID(v uint32) *AiUsageLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AiUsageLogUpdate) SetNillableUserID(v *uint32) *AiUsageLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AiUsageLogUpdate) AddUserID(v int32) *AiUsageLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AiUsageLogUpdate) ClearUserID() *AiUsageLogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *AiUsageLogUpdate) SetModelName(v string) *AiUsageLogUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *AiUsageLogUpdate) SetNillableModelName(v *string) *AiUsageLogUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// ClearModelName clears the value of the "model_name" field.
func (_u *AiUsageLogUpdate) ClearModelName() *AiUsageLogUpdate {
	_u.mutation.ClearModelName()
	return _u
}

// SetPromptTokens sets the "prompt_tokens" field.
func (_u *AiUsageLogUpdate) SetPromptTokens(v uint32) *AiUsageLogUpdate {
	_u.mutation.ResetPromptTokens()
	_u.mutation.SetPromptTokens(v)
	return _u
}

// SetNillablePromptTokens sets the "prompt_tokens" field if the given value is not nil.
func (_u *AiUsageLogUpdate) SetNillablePromptTokens(v *uint32) *AiUsageLogUpdate {
	if v != nil {
		_u.SetPromptTokens(*v)
	}
	return _u
}

// AddPromptTokens adds value to the "prompt_tokens" field.
func (_u *AiUsageLogUpdate) AddPromptTokens(v int32) *AiUsageLogUpdate {
	_u.mutation.AddPromptTokens(v)
	return _u
}

// ClearPromptTokens clears the value of the "prompt_tokens" field.
func (_u *AiUsageLogUpdate) ClearPromptTokens() *AiUsageLogUpdate {
	_u.mutation.ClearPromptTokens()
	return _u
}

// SetCompletionTokens sets the "completion_tokens" field.
func (_u *AiUsageLogUpdate) SetCompletionTokens(v uint32) *AiUsageLogUpdate {
	_u.mutation.ResetCompletionTokens()
	_u.mutation.SetCompletionTokens(v)
	return _u
}

// SetNillableCompletionTokens sets the "completion_tokens" field if the given value is not nil.
func (_u *AiUsageLogUpdate) SetNillableCompletionTokens(v *uint32) *AiUsageLogUpdate {
	if v != nil {
		_u.SetCompletionTokens(*v)
	}
	return _u
}

// AddCompletionTokens adds value to the "completion_tokens" field.
func (_u *AiUsageLogUpdate) AddCompletionTokens(v int32) *AiUsageLogUpdate {
	_u.mutation.AddCompletionTokens(v)
	return _u
}

// ClearCompletionTokens clears the value of the "completion_tokens" field.
func (_u *AiUsageLogUpdate) ClearCompletionTokens() *AiUsageLogUpdate {
	_u.mutation.ClearCompletionTokens()
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *AiUsageLogUpdate) SetTotalTokens(v uint32) *AiUsageLogUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *AiUsageLogUpdate) SetNillableTotalTokens(v *uint32) *AiUsageLogUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *AiUsageLogUpdate) AddTotalTokens(v int32) *AiUsageLogUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// ClearTotalTokens clears the value of the "total_tokens" field.
func (_u *AiUsageLogUpdate) ClearTotalTokens() *AiUsageLogUpdate {
	_u.mutation.ClearTotalTokens()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AiUsageLogUpdate) SetDurationMs(v uint32) *AiUsageLogUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AiUsageLogUpdate) SetNillableDurationMs(v *uint32) *AiUsageLogUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AiUsageLogUpdate) AddDurationMs(v int32) *AiUsageLogUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AiUsageLogUpdate) ClearDurationMs() *AiUsageLogUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// Mutation returns the AiUsageLogMutation object of the builder.
func (_u *AiUsageLogUpdate) Mutation() *AiUsageLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AiUsageLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AiUsageLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AiUsageLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AiUsageLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AiUsageLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AiUsageLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AiUsageLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(aiusagelog.Table, aiusagelog.Columns, sqlgraph.NewFieldSpec(aiusagelog.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(aiusagelog.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(aiusagelog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(aiusagelog.FieldProviderID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedProviderID(); ok {
		_spec.AddField(aiusagelog.FieldProviderID, field.TypeUint32, value)
	}
	if _u.mutation.ProviderIDCleared() {
		_spec.ClearField(aiusagelog.FieldProviderID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(aiusagelog.FieldConversationID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(aiusagelog.FieldConversationID, field.TypeUint32, value)
	}
	if _u.mutation.ConversationIDCleared() {
		_spec.ClearField(aiusagelog.FieldConversationID, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(aiusagelog.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(aiusagelog.FieldUserID, field.TypeUint32, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(aiusagelog.FieldUserID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(aiusagelog.FieldModelName, field.TypeString, value)
	}
	if _u.mutation.ModelNameCleared() {
		_spec.ClearField(aiusagelog.FieldModelName, field.TypeString)
	}
	if value, ok := _u.mutation.PromptTokens(); ok {
		_spec.SetField(aiusagelog.FieldPromptTokens, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPromptTokens(); ok {
		_spec.AddField(aiusagelog.FieldPromptTokens, field.TypeUint32, value)
	}
	if _u.mutation.PromptTokensCleared() {
		_spec.ClearField(aiusagelog.FieldPromptTokens, field.TypeUint32)
	}
	if value, ok := _u.mutation.CompletionTokens(); ok {
		_spec.SetField(aiusagelog.FieldCompletionTokens, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCompletionTokens(); ok {
		_spec.AddField(aiusagelog.FieldCompletionTokens, field.TypeUint32, value)
	}
	if _u.mutation.CompletionTokensCleared() {
		_spec.ClearField(aiusagelog.FieldCompletionTokens, field.TypeUint32)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(aiusagelog.FieldTotalTokens, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(aiusagelog.FieldTotalTokens, field.TypeUint32, value)
	}
	if _u.mutation.TotalTokensCleared() {
		_spec.ClearField(aiusagelog.FieldTotalTokens, field.TypeUint32)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(aiusagelog.FieldDurationMs, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(aiusagelog.FieldDurationMs, field.TypeUint32, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(aiusagelog.FieldDurationMs, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiusagelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AiUsageLogUpdateOne is the builder for updating a single AiUsageLog entity.
type AiUsageLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AiUsageLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetProviderID sets the "provider_id" field.
func (_u *AiUsageLogUpdateOne) SetProviderID(v uint32) *AiUsageLogUpdateOne {
	_u.mutation.ResetProviderID()
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *AiUsageLogUpdateOne) SetNillableProviderID(v *uint32) *AiUsageLogUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// AddProviderID adds value to the "provider_id" field.
func (_u *AiUsageLogUpdateOne) AddProviderID(v int32) *AiUsageLogUpdateOne {
	_u.mutation.AddProviderID(v)
	return _u
}

// ClearProviderID clears the value of the "provider_id" field.
func (_u *AiUsageLogUpdateOne) ClearProviderID() *AiUsageLogUpdateOne {
	_u.mutation.ClearProviderID()
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *AiUsageLogUpdateOne) SetConversationID(v uint32) *AiUsageLogUpdateOne {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *AiUsageLogUpdateOne) SetNillableConversationID(v *uint32) *AiUsageLogUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *AiUsageLogUpdateOne) AddConversationID(v int32) *AiUsageLogUpdateOne {
	_u.mutation.AddConversationID(v)
	return _u
}

// ClearConversationID clears the value of the "conversation_id" field.
func (_u *AiUsageLogUpdateOne) ClearConversationID() *AiUsageLogUpdateOne {
	_u.mutation.ClearConversationID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AiUsageLogUpdateOne) SetUserID(v uint32) *AiUsageLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AiUsageLogUpdateOne) SetNillableUserID(v *uint32) *AiUsageLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AiUsageLogUpdateOne) AddUserID(v int32) *AiUsageLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AiUsageLogUpdateOne) ClearUserID() *AiUsageLogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *AiUsageLogUpdateOne) SetModelName(v string) *AiUsageLogUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *AiUsageLogUpdateOne) SetNillableModelName(v *string) *AiUsageLogUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// ClearModelName clears the value of the "model_name" field.
func (_u *AiUsageLogUpdateOne) ClearModelName() *AiUsageLogUpdateOne {
	_u.mutation.ClearModelName()
	return _u
}

// SetPromptTokens sets the "prompt_tokens" field.
func (_u *AiUsageLogUpdateOne) SetPromptTokens(v uint32) *AiUsageLogUpdateOne {
	_u.mutation.ResetPromptTokens()
	_u.mutation.SetPromptTokens(v)
	return _u
}

// SetNillablePromptTokens sets the "prompt_tokens" field if the given value is not nil.
func (_u *AiUsageLogUpdateOne) SetNillablePromptTokens(v *uint32) *AiUsageLogUpdateOne {
	if v != nil {
		_u.SetPromptTokens(*v)
	}
	return _u
}

// AddPromptTokens adds value to the "prompt_tokens" field.
func (_u *AiUsageLogUpdateOne) AddPromptTokens(v int32) *AiUsageLogUpdateOne {
	_u.mutation.AddPromptTokens(v)
	return _u
}

// ClearPromptTokens clears the value of the "prompt_tokens" field.
func (_u *AiUsageLogUpdateOne) ClearPromptTokens() *AiUsageLogUpdateOne {
	_u.mutation.ClearPromptTokens()
	return _u
}

// SetCompletionTokens sets the "completion_tokens" field.
func (_u *AiUsageLogUpdateOne) SetCompletionTokens(v uint32) *AiUsageLogUpdateOne {
	_u.mutation.ResetCompletionTokens()
	_u.mutation.SetCompletionTokens(v)
	return _u
}

// SetNillableCompletionTokens sets the "completion_tokens" field if the given value is not nil.
func (_u *AiUsageLogUpdateOne) SetNillableCompletionTokens(v *uint32) *AiUsageLogUpdateOne {
	if v != nil {
		_u.SetCompletionTokens(*v)
	}
	return _u
}

// AddCompletionTokens adds value to the "completion_tokens" field.
func (_u *AiUsageLogUpdateOne) AddCompletionTokens(v int32) *AiUsageLogUpdateOne {
	_u.mutation.AddCompletionTokens(v)
	return _u
}

// ClearCompletionTokens clears the value of the "completion_tokens" field.
func (_u *AiUsageLogUpdateOne) ClearCompletionTokens() *AiUsageLogUpdateOne {
	_u.mutation.ClearCompletionTokens()
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *AiUsageLogUpdateOne) SetTotalTokens(v uint32) *AiUsageLogUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *AiUsageLogUpdateOne) SetNillableTotalTokens(v *uint32) *AiUsageLogUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *AiUsageLogUpdateOne) AddTotalTokens(v int32) *AiUsageLogUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// ClearTotalTokens clears the value of the "total_tokens" field.
func (_u *AiUsageLogUpdateOne) ClearTotalTokens() *AiUsageLogUpdateOne {
	_u.mutation.ClearTotalTokens()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AiUsageLogUpdateOne) SetDurationMs(v uint32) *AiUsageLogUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AiUsageLogUpdateOne) SetNillableDurationMs(v *uint32) *AiUsageLogUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AiUsageLogUpdateOne) AddDurationMs(v int32) *AiUsageLogUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AiUsageLogUpdateOne) ClearDurationMs() *AiUsageLogUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// Mutation returns the AiUsageLogMutation object of the builder.
func (_u *AiUsageLogUpdateOne) Mutation() *AiUsageLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the AiUsageLogUpdate builder.
func (_u *AiUsageLogUpdateOne) Where(ps ...predicate.AiUsageLog) *AiUsageLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AiUsageLogUpdateOne) Select(field string, fields ...string) *AiUsageLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AiUsageLog entity.
func (_u *AiUsageLogUpdateOne) Save(ctx context.Context) (*AiUsageLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AiUsageLogUpdateOne) SaveX(ctx context.Context) *AiUsageLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AiUsageLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AiUsageLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AiUsageLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AiUsageLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AiUsageLogUpdateOne) sqlSave(ctx context.Context) (_node *AiUsageLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(aiusagelog.Table, aiusagelog.Columns, sqlgraph.NewFieldSpec(aiusagelog.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AiUsageLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aiusagelog.FieldID)
		for _, f := range fields {
			if !aiusagelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aiusagelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(aiusagelog.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(aiusagelog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(aiusagelog.FieldProviderID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedProviderID(); ok {
		_spec.AddField(aiusagelog.FieldProviderID, field.TypeUint32, value)
	}
	if _u.mutation.ProviderIDCleared() {
		_spec.ClearField(aiusagelog.FieldProviderID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(aiusagelog.FieldConversationID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(aiusagelog.FieldConversationID, field.TypeUint32, value)
	}
	if _u.mutation.ConversationIDCleared() {
		_spec.ClearField(aiusagelog.FieldConversationID, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(aiusagelog.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(aiusagelog.FieldUserID, field.TypeUint32, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(aiusagelog.FieldUserID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(aiusagelog.FieldModelName, field.TypeString, value)
	}
	if _u.mutation.ModelNameCleared() {
		_spec.ClearField(aiusagelog.FieldModelName, field.TypeString)
	}
	if value, ok := _u.mutation.PromptTokens(); ok {
		_spec.SetField(aiusagelog.FieldPromptTokens, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPromptTokens(); ok {
		_spec.AddField(aiusagelog.FieldPromptTokens, field.TypeUint32, value)
	}
	if _u.mutation.PromptTokensCleared() {
		_spec.ClearField(aiusagelog.FieldPromptTokens, field.TypeUint32)
	}
	if value, ok := _u.mutation.CompletionTokens(); ok {
		_spec.SetField(aiusagelog.FieldCompletionTokens, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCompletionTokens(); ok {
		_spec.AddField(aiusagelog.FieldCompletionTokens, field.TypeUint32, value)
	}
	if _u.mutation.CompletionTokensCleared() {
		_spec.ClearField(aiusagelog.FieldCompletionTokens, field.TypeUint32)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(aiusagelog.FieldTotalTokens, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(aiusagelog.FieldTotalTokens, field.TypeUint32, value)
	}
	if _u.mutation.TotalTokensCleared() {
		_spec.ClearField(aiusagelog.FieldTotalTokens, field.TypeUint32)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(aiusagelog.FieldDurationMs, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(aiusagelog.FieldDurationMs, field.TypeUint32, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(aiusagelog.FieldDurationMs, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &AiUsageLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aiusagelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
