// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/notificationpreference"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// NotificationPreferenceUpdate is the builder for updating NotificationPreference entities.
type NotificationPreferenceUpdate struct {
	config
	hooks     []Hook
	mutation  *NotificationPreferenceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NotificationPreferenceUpdate builder.
func (_u *NotificationPreferenceUpdate) Where(ps ...predicate.NotificationPreference) *NotificationPreferenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationPreferenceUpdate) SetUpdatedAt(v time.Time) *NotificationPreferenceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NotificationPreferenceUpdate) SetNillableUpdatedAt(v *time.Time) *NotificationPreferenceUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *NotificationPreferenceUpdate) ClearUpdatedAt() *NotificationPreferenceUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *NotificationPreferenceUpdate) SetDeletedAt(v time.Time) *NotificationPreferenceUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *NotificationPreferenceUpdate) SetNillableDeletedAt(v *time.Time) *NotificationPreferenceUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *NotificationPreferenceUpdate) ClearDeletedAt() *NotificationPreferenceUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *NotificationPreferenceUpdate) SetCreatedBy(v uint32) *NotificationPreferenceUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *NotificationPreferenceUpdate) SetNillableCreatedBy(v *uint32) *NotificationPreferenceUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *NotificationPreferenceUpdate) AddCreatedBy(v int32) *NotificationPreferenceUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *NotificationPreferenceUpdate) ClearCreatedBy() *NotificationPreferenceUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *NotificationPreferenceUpdate) SetUpdatedBy(v uint32) *NotificationPreferenceUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *NotificationPreferenceUpdate) SetNillableUpdatedBy(v *uint32) *NotificationPreferenceUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *NotificationPreferenceUpdate) AddUpdatedBy(v int32) *NotificationPreferenceUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *NotificationPreferenceUpdate) ClearUpdatedBy() *NotificationPreferenceUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *NotificationPreferenceUpdate) SetDeletedBy(v uint32) *NotificationPreferenceUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *NotificationPreferenceUpdate) SetNillableDeletedBy(v *uint32) *NotificationPreferenceUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *NotificationPreferenceUpdate) AddDeletedBy(v int32) *NotificationPreferenceUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *NotificationPreferenceUpdate) ClearDeletedBy() *NotificationPreferenceUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NotificationPreferenceUpdate) SetUserID(v uint32) *NotificationPreferenceUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotificationPreferenceUpdate) SetNillableUserID(v *uint32) *NotificationPreferenceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *NotificationPreferenceUpdate) AddUserID(v int32) *NotificationPreferenceUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetQuietEnabled sets the "quiet_enabled" field.
func (_u *NotificationPreferenceUpdate) SetQuietEnabled(v bool) *NotificationPreferenceUpdate {
	_u.mutation.SetQuietEnabled(v)
	return _u
}

// SetNillableQuietEnabled sets the "quiet_enabled" field if the given value is not nil.
func (_u *NotificationPreferenceUpdate) SetNillableQuietEnabled(v *bool) *NotificationPreferenceUpdate {
	if v != nil {
		_u.SetQuietEnabled(*v)
	}
	return _u
}

// SetQuietStartMinute sets the "quiet_start_minute" field.
func (_u *NotificationPreferenceUpdate) SetQuietStartMinute(v int32) *NotificationPreferenceUpdate {
	_u.mutation.ResetQuietStartMinute()
	_u.mutation.SetQuietStartMinute(v)
	return _u
}

// SetNillableQuietStartMinute sets the "quiet_start_minute" field if the given value is not nil.
func (_u *NotificationPreferenceUpdate) SetNillableQuietStartMinute(v *int32) *NotificationPreferenceUpdate {
	if v != nil {
		_u.SetQuietStartMinute(*v)
	}
	return _u
}

// AddQuietStartMinute adds value to the "quiet_start_minute" field.
func (_u *NotificationPreferenceUpdate) AddQuietStartMinute(v int32) *NotificationPreferenceUpdate {
	_u.mutation.AddQuietStartMinute(v)
	return _u
}

// SetQuietEndMinute sets the "quiet_end_minute" field.
func (_u *NotificationPreferenceUpdate) SetQuietEndMinute(v int32) *NotificationPreferenceUpdate {
	_u.mutation.ResetQuietEndMinute()
	_u.mutation.SetQuietEndMinute(v)
	return _u
}

// SetNillableQuietEndMinute sets the "quiet_end_minute" field if the given value is not nil.
func (_u *NotificationPreferenceUpdate) SetNillableQuietEndMinute(v *int32) *NotificationPreferenceUpdate {
	if v != nil {
		_u.SetQuietEndMinute(*v)
	}
	return _u
}

// AddQuietEndMinute adds value to the "quiet_end_minute" field.
func (_u *NotificationPreferenceUpdate) AddQuietEndMinute(v int32) *NotificationPreferenceUpdate {
	_u.mutation.AddQuietEndMinute(v)
	return _u
}

// SetMutedCategoryIds sets the "muted_category_ids" field.
func (_u *NotificationPreferenceUpdate) SetMutedCategoryIds(v []uint32) *NotificationPreferenceUpdate {
	_u.mutation.SetMutedCategoryIds(v)
	return _u
}

// AppendMutedCategoryIds appends value to the "muted_category_ids" field.
func (_u *NotificationPreferenceUpdate) AppendMutedCategoryIds(v []uint32) *NotificationPreferenceUpdate {
	_u.mutation.AppendMutedCategoryIds(v)
	return _u
}

// ClearMutedCategoryIds clears the value of the "muted_category_ids" field.
func (_u *NotificationPreferenceUpdate) ClearMutedCategoryIds() *NotificationPreferenceUpdate {
	_u.mutation.ClearMutedCategoryIds()
	return _u
}

// Mutation returns the NotificationPreferenceMutation object of the builder.
func (_u *NotificationPreferenceUpdate) Mutation() *NotificationPreferenceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationPreferenceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationPreferenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationPreferenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationPreferenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *NotificationPreferenceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationPreferenceUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *NotificationPreferenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(notificationpreference.Table, notificationpreference.Columns, sqlgraph.NewFieldSpec(notificationpreference.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(notificationpreference.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationpreference.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(notificationpreference.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(notificationpreference.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(notificationpreference.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(notificationpreference.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(notificationpreference.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(notificationpreference.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(notificationpreference.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(notificationpreference.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(notificationpreference.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(notificationpreference.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(notificationpreference.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(notificationpreference.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(notificationpreference.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(notificationpreference.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.QuietEnabled(); ok {
		_spec.SetField(notificationpreference.FieldQuietEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QuietStartMinute(); ok {
		_spec.SetField(notificationpreference.FieldQuietStartMinute, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedQuietStartMinute(); ok {
		_spec.AddField(notificationpreference.FieldQuietStartMinute, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.QuietEndMinute(); ok {
		_spec.SetField(notificationpreference.FieldQuietEndMinute, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedQuietEndMinute(); ok {
		_spec.AddField(notificationpreference.FieldQuietEndMinute, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.MutedCategoryIds(); ok {
		_spec.SetField(notificationpreference.FieldMutedCategoryIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMutedCategoryIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notificationpreference.FieldMutedCategoryIds, value)
		})
	}
	if _u.mutation.MutedCategoryIdsCleared() {
		_spec.ClearField(notificationpreference.FieldMutedCategoryIds, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationpreference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationPreferenceUpdateOne is the builder for updating a single NotificationPreference entity.
type NotificationPreferenceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NotificationPreferenceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationPreferenceUpdateOne) SetUpdatedAt(v time.Time) *NotificationPreferenceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NotificationPreferenceUpdateOne) SetNillableUpdatedAt(v *time.Time) *NotificationPreferenceUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *NotificationPreferenceUpdateOne) ClearUpdatedAt() *NotificationPreferenceUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *NotificationPreferenceUpdateOne) SetDeletedAt(v time.Time) *NotificationPreferenceUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *NotificationPreferenceUpdateOne) SetNillableDeletedAt(v *time.Time) *NotificationPreferenceUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *NotificationPreferenceUpdateOne) ClearDeletedAt() *NotificationPreferenceUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *NotificationPreferenceUpdateOne) SetCreatedBy(v uint32) *NotificationPreferenceUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *NotificationPreferenceUpdateOne) SetNillableCreatedBy(v *uint32) *NotificationPreferenceUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *NotificationPreferenceUpdateOne) AddCreatedBy(v int32) *NotificationPreferenceUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *NotificationPreferenceUpdateOne) ClearCreatedBy() *NotificationPreferenceUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *NotificationPreferenceUpdateOne) SetUpdatedBy(v uint32) *NotificationPreferenceUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *NotificationPreferenceUpdateOne) SetNillableUpdatedBy(v *uint32) *NotificationPreferenceUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *NotificationPreferenceUpdateOne) AddUpdatedBy(v int32) *NotificationPreferenceUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *NotificationPreferenceUpdateOne) ClearUpdatedBy() *NotificationPreferenceUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *NotificationPreferenceUpdateOne) SetDeletedBy(v uint32) *NotificationPreferenceUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *NotificationPreferenceUpdateOne) SetNillableDeletedBy(v *uint32) *NotificationPreferenceUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *NotificationPreferenceUpdateOne) AddDeletedBy(v int32) *NotificationPreferenceUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *NotificationPreferenceUpdateOne) ClearDeletedBy() *NotificationPreferenceUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NotificationPreferenceUpdateOne) SetUserID(v uint32) *NotificationPreferenceUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotificationPreferenceUpdateOne) SetNillableUserID(v *uint32) *NotificationPreferenceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *NotificationPreferenceUpdateOne) AddUserID(v int32) *NotificationPreferenceUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetQuietEnabled sets the "quiet_enabled" field.
func (_u *NotificationPreferenceUpdateOne) SetQuietEnabled(v bool) *NotificationPreferenceUpdateOne {
	_u.mutation.SetQuietEnabled(v)
	return _u
}

// SetNillableQuietEnabled sets the "quiet_enabled" field if the given value is not nil.
func (_u *NotificationPreferenceUpdateOne) SetNillableQuietEnabled(v *bool) *NotificationPreferenceUpdateOne {
	if v != nil {
		_u.SetQuietEnabled(*v)
	}
	return _u
}

// SetQuietStartMinute sets the "quiet_start_minute" field.
func (_u *NotificationPreferenceUpdateOne) SetQuietStartMinute(v int32) *NotificationPreferenceUpdateOne {
	_u.mutation.ResetQuietStartMinute()
	_u.mutation.SetQuietStartMinute(v)
	return _u
}

// SetNillableQuietStartMinute sets the "quiet_start_minute" field if the given value is not nil.
func (_u *NotificationPreferenceUpdateOne) SetNillableQuietStartMinute(v *int32) *NotificationPreferenceUpdateOne {
	if v != nil {
		_u.SetQuietStartMinute(*v)
	}
	return _u
}

// AddQuietStartMinute adds value to the "quiet_start_minute" field.
func (_u *NotificationPreferenceUpdateOne) AddQuietStartMinute(v int32) *NotificationPreferenceUpdateOne {
	_u.mutation.AddQuietStartMinute(v)
	return _u
}

// SetQuietEndMinute sets the "quiet_end_minute" field.
func (_u *NotificationPreferenceUpdateOne) SetQuietEndMinute(v int32) *NotificationPreferenceUpdateOne {
	_u.mutation.ResetQuietEndMinute()
	_u.mutation.SetQuietEndMinute(v)
	return _u
}

// SetNillableQuietEndMinute sets the "quiet_end_minute" field if the given value is not nil.
func (_u *NotificationPreferenceUpdateOne) SetNillableQuietEndMinute(v *int32) *NotificationPreferenceUpdateOne {
	if v != nil {
		_u.SetQuietEndMinute(*v)
	}
	return _u
}

// AddQuietEndMinute adds value to the "quiet_end_minute" field.
func (_u *NotificationPreferenceUpdateOne) AddQuietEndMinute(v int32) *NotificationPreferenceUpdateOne {
	_u.mutation.AddQuietEndMinute(v)
	return _u
}

// SetMutedCategoryIds sets the "muted_category_ids" field.
func (_u *NotificationPreferenceUpdateOne) SetMutedCategoryIds(v []uint32) *NotificationPreferenceUpdateOne {
	_u.mutation.SetMutedCategoryIds(v)
	return _u
}

// AppendMutedCategoryIds appends value to the "muted_category_ids" field.
func (_u *NotificationPreferenceUpdateOne) AppendMutedCategoryIds(v []uint32) *NotificationPreferenceUpdateOne {
	_u.mutation.AppendMutedCategoryIds(v)
	return _u
}

// ClearMutedCategoryIds clears the value of the "muted_category_ids" field.
func (_u *NotificationPreferenceUpdateOne) ClearMutedCategoryIds() *NotificationPreferenceUpdateOne {
	_u.mutation.ClearMutedCategoryIds()
	return _u
}

// Mutation returns the NotificationPreferenceMutation object of the builder.
func (_u *NotificationPreferenceUpdateOne) Mutation() *NotificationPreferenceMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationPreferenceUpdate builder.
func (_u *NotificationPreferenceUpdateOne) Where(ps ...predicate.NotificationPreference) *NotificationPreferenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationPreferenceUpdateOne) Select(field string, fields ...string) *NotificationPreferenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationPreference entity.
func (_u *NotificationPreferenceUpdateOne) Save(ctx context.Context) (*NotificationPreference, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationPreferenceUpdateOne) SaveX(ctx context.Context) *NotificationPreference {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationPreferenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationPreferenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *NotificationPreferenceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationPreferenceUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *NotificationPreferenceUpdateOne) sqlSave(ctx context.Context) (_node *NotificationPreference, err error) {
	_spec := sqlgraph.NewUpdateSpec(notificationpreference.Table, notificationpreference.Columns, sqlgraph.NewFieldSpec(notificationpreference.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationPreference.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationpreference.FieldID)
		for _, f := range fields {
			if !notificationpreference.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationpreference.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(notificationpreference.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationpreference.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(notificationpreference.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(notificationpreference.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(notificationpreference.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(notificationpreference.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(notificationpreference.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(notificationpreference.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(notificationpreference.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(notificationpreference.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(notificationpreference.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(notificationpreference.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(notificationpreference.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(notificationpreference.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(notificationpreference.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(notificationpreference.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.QuietEnabled(); ok {
		_spec.SetField(notificationpreference.FieldQuietEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QuietStartMinute(); ok {
		_spec.SetField(notificationpreference.FieldQuietStartMinute, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedQuietStartMinute(); ok {
		_spec.AddField(notificationpreference.FieldQuietStartMinute, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.QuietEndMinute(); ok {
		_spec.SetField(notificationpreference.FieldQuietEndMinute, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedQuietEndMinute(); ok {
		_spec.AddField(notificationpreference.FieldQuietEndMinute, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.MutedCategoryIds(); ok {
		_spec.SetField(notificationpreference.FieldMutedCategoryIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMutedCategoryIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notificationpreference.FieldMutedCategoryIds, value)
		})
	}
	if _u.mutation.MutedCategoryIdsCleared() {
		_spec.ClearField(notificationpreference.FieldMutedCategoryIds, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &NotificationPreference{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationpreference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
