// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/notificationpreference"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 用户通知偏好表（静音时段 + 分类退订）
type NotificationPreference struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 用户ID（唯一，每用户一行）
	UserID uint32 `json:"user_id,omitempty"`
	// 是否启用实时推送静音时段（只抑制 SSE 实时推送，收件行照常落库）
	QuietEnabled bool `json:"quiet_enabled,omitempty"`
	// 静音开始：自当日 00:00 起的分钟数（0-1439）
	QuietStartMinute int32 `json:"quiet_start_minute,omitempty"`
	// 静音结束：自当日 00:00 起的分钟数（0-1439）；跨零点窗口 start > end 合法
	QuietEndMinute int32 `json:"quiet_end_minute,omitempty"`
	// 退订的站内信分类ID列表（仅约束全员广播，点对点定向发送不受影响）
	MutedCategoryIds []uint32 `json:"muted_category_ids,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationPreference) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationpreference.FieldMutedCategoryIds:
			values[i] = new([]byte)
		case notificationpreference.FieldQuietEnabled:
			values[i] = new(sql.NullBool)
		case notificationpreference.FieldID, notificationpreference.FieldCreatedBy, notificationpreference.FieldUpdatedBy, notificationpreference.FieldDeletedBy, notificationpreference.FieldUserID, notificationpreference.FieldQuietStartMinute, notificationpreference.FieldQuietEndMinute:
			values[i] = new(sql.NullInt64)
		case notificationpreference.FieldCreatedAt, notificationpreference.FieldUpdatedAt, notificationpreference.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationPreference fields.
func (_m *NotificationPreference) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationpreference.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case notificationpreference.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case notificationpreference.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case notificationpreference.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case notificationpreference.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case notificationpreference.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case notificationpreference.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case notificationpreference.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint32(value.Int64)
			}
		case notificationpreference.FieldQuietEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field quiet_enabled", values[i])
			} else if value.Valid {
				_m.QuietEnabled = value.Bool
			}
		case notificationpreference.FieldQuietStartMinute:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quiet_start_minute", values[i])
			} else if value.Valid {
				_m.QuietStartMinute = int32(value.Int64)
			}
		case notificationpreference.FieldQuietEndMinute:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quiet_end_minute", values[i])
			} else if value.Valid {
				_m.QuietEndMinute = int32(value.Int64)
			}
		case notificationpreference.FieldMutedCategoryIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field muted_category_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MutedCategoryIds); err != nil {
					return fmt.Errorf("unmarshal field muted_category_ids: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationPreference.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationPreference) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NotificationPreference.
// Note that you need to call NotificationPreference.Unwrap() before calling this method if this NotificationPreference
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationPreference) Update() *NotificationPreferenceUpdateOne {
	return NewNotificationPreferenceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationPreference entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationPreference) Unwrap() *NotificationPreference {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationPreference is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationPreference) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationPreference(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("quiet_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuietEnabled))
	builder.WriteString(", ")
	builder.WriteString("quiet_start_minute=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuietStartMinute))
	builder.WriteString(", ")
	builder.WriteString("quiet_end_minute=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuietEndMinute))
	builder.WriteString(", ")
	builder.WriteString("muted_category_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.MutedCategoryIds))
	builder.WriteByte(')')
	return builder.String()
}

// NotificationPreferences is a parsable slice of NotificationPreference.
type NotificationPreferences []*NotificationPreference
