// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/notificationpreference"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationPreferenceCreate is the builder for creating a NotificationPreference entity.
type NotificationPreferenceCreate struct {
	config
	mutation *NotificationPreferenceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationPreferenceCreate) SetCreatedAt(v time.Time) *NotificationPreferenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableCreatedAt(v *time.Time) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationPreferenceCreate) SetUpdatedAt(v time.Time) *NotificationPreferenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableUpdatedAt(v *time.Time) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *NotificationPreferenceCreate) SetDeletedAt(v time.Time) *NotificationPreferenceCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableDeletedAt(v *time.Time) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *NotificationPreferenceCreate) SetCreatedBy(v uint32) *NotificationPreferenceCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableCreatedBy(v *uint32) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *NotificationPreferenceCreate) SetUpdatedBy(v uint32) *NotificationPreferenceCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableUpdatedBy(v *uint32) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *NotificationPreferenceCreate) SetDeletedBy(v uint32) *NotificationPreferenceCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableDeletedBy(v *uint32) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *NotificationPreferenceCreate) SetUserID(v uint32) *NotificationPreferenceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetQuietEnabled sets the "quiet_enabled" field.
func (_c *NotificationPreferenceCreate) SetQuietEnabled(v bool) *NotificationPreferenceCreate {
	_c.mutation.SetQuietEnabled(v)
	return _c
}

// SetNillableQuietEnabled sets the "quiet_enabled" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableQuietEnabled(v *bool) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetQuietEnabled(*v)
	}
	return _c
}

// SetQuietStartMinute sets the "quiet_start_minute" field.
func (_c *NotificationPreferenceCreate) SetQuietStartMinute(v int32) *NotificationPreferenceCreate {
	_c.mutation.SetQuietStartMinute(v)
	return _c
}

// SetNillableQuietStartMinute sets the "quiet_start_minute" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableQuietStartMinute(v *int32) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetQuietStartMinute(*v)
	}
	return _c
}

// SetQuietEndMinute sets the "quiet_end_minute" field.
func (_c *NotificationPreferenceCreate) SetQuietEndMinute(v int32) *NotificationPreferenceCreate {
	_c.mutation.SetQuietEndMinute(v)
	return _c
}

// SetNillableQuietEndMinute sets the "quiet_end_minute" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableQuietEndMinute(v *int32) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetQuietEndMinute(*v)
	}
	return _c
}

// SetMutedCategoryIds sets the "muted_category_ids" field.
func (_c *NotificationPreferenceCreate) SetMutedCategoryIds(v []uint32) *NotificationPreferenceCreate {
	_c.mutation.SetMutedCategoryIds(v)
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationPreferenceCreate) SetID(v uint32) *NotificationPreferenceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NotificationPreferenceMutation object of the builder.
func (_c *NotificationPreferenceCreate) Mutation() *NotificationPreferenceMutation {
	return _c.mutation
}

// Save creates the NotificationPreference in the database.
func (_c *NotificationPreferenceCreate) Save(ctx context.Context) (*NotificationPreference, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationPreferenceCreate) SaveX(ctx context.Context) *NotificationPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationPreferenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationPreferenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationPreferenceCreate) defaults() {
	if _, ok := _c.mutation.QuietEnabled(); !ok {
		v := notificationpreference.DefaultQuietEnabled
		_c.mutation.SetQuietEnabled(v)
	}
	if _, ok := _c.mutation.QuietStartMinute(); !ok {
		v := notificationpreference.DefaultQuietStartMinute
		_c.mutation.SetQuietStartMinute(v)
	}
	if _, ok := _c.mutation.QuietEndMinute(); !ok {
		v := notificationpreference.DefaultQuietEndMinute
		_c.mutation.SetQuietEndMinute(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationPreferenceCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "NotificationPreference.user_id"`)}
	}
	if _, ok := _c.mutation.QuietEnabled(); !ok {
		return &ValidationError{Name: "quiet_enabled", err: errors.New(`ent: missing required field "NotificationPreference.quiet_enabled"`)}
	}
	if _, ok := _c.mutation.QuietStartMinute(); !ok {
		return &ValidationError{Name: "quiet_start_minute", err: errors.New(`ent: missing required field "NotificationPreference.quiet_start_minute"`)}
	}
	if _, ok := _c.mutation.QuietEndMinute(); !ok {
		return &ValidationError{Name: "quiet_end_minute", err: errors.New(`ent: missing required field "NotificationPreference.quiet_end_minute"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := notificationpreference.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "NotificationPreference.id": %w`, err)}
		}
	}
	return nil
}

func (_c *NotificationPreferenceCreate) sqlSave(ctx context.Context) (*NotificationPreference, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationPreferenceCreate) createSpec() (*NotificationPreference, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationPreference{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationpreference.Table, sqlgraph.NewFieldSpec(notificationpreference.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notificationpreference.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationpreference.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(notificationpreference.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(notificationpreference.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(notificationpreference.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(notificationpreference.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(notificationpreference.FieldUserID, field.TypeUint32, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.QuietEnabled(); ok {
		_spec.SetField(notificationpreference.FieldQuietEnabled, field.TypeBool, value)
		_node.QuietEnabled = value
	}
	if value, ok := _c.mutation.QuietStartMinute(); ok {
		_spec.SetField(notificationpreference.FieldQuietStartMinute, field.TypeInt32, value)
		_node.QuietStartMinute = value
	}
	if value, ok := _c.mutation.QuietEndMinute(); ok {
		_spec.SetField(notificationpreference.FieldQuietEndMinute, field.TypeInt32, value)
		_node.QuietEndMinute = value
	}
	if value, ok := _c.mutation.MutedCategoryIds(); ok {
		_spec.SetField(notificationpreference.FieldMutedCategoryIds, field.TypeJSON, value)
		_node.MutedCategoryIds = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationPreference.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationPreferenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationPreferenceCreate) OnConflict(opts ...sql.ConflictOption) *NotificationPreferenceUpsertOne {
	_c.conflict = opts
	return &NotificationPreferenceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationPreferenceCreate) OnConflictColumns(columns ...string) *NotificationPreferenceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationPreferenceUpsertOne{
		create: _c,
	}
}

type (
	// NotificationPreferenceUpsertOne is the builder for "upsert"-ing
	//  one NotificationPreference node.
	NotificationPreferenceUpsertOne struct {
		create *NotificationPreferenceCreate
	}

	// NotificationPreferenceUpsert is the "OnConflict" setter.
	NotificationPreferenceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationPreferenceUpsert) SetUpdatedAt(v time.Time) *NotificationPreferenceUpsert {
	u.Set(notificationpreference.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationPreferenceUpsert) UpdateUpdatedAt() *NotificationPreferenceUpsert {
	u.SetExcluded(notificationpreference.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *NotificationPreferenceUpsert) ClearUpdatedAt() *NotificationPreferenceUpsert {
	u.SetNull(notificationpreference.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *NotificationPreferenceUpsert) SetDeletedAt(v time.Time) *NotificationPreferenceUpsert {
	u.Set(notificationpreference.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *NotificationPreferenceUpsert) UpdateDeletedAt() *NotificationPreferenceUpsert {
	u.SetExcluded(notificationpreference.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *NotificationPreferenceUpsert) ClearDeletedAt() *NotificationPreferenceUpsert {
	u.SetNull(notificationpreference.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *NotificationPreferenceUpsert) SetCreatedBy(v uint32) *NotificationPreferenceUpsert {
	u.Set(notificationpreference.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *NotificationPreferenceUpsert) UpdateCreatedBy() *NotificationPreferenceUpsert {
	u.SetExcluded(notificationpreference.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *NotificationPreferenceUpsert) AddCreatedBy(v uint32) *NotificationPreferenceUpsert {
	u.Add(notificationpreference.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *NotificationPreferenceUpsert) ClearCreatedBy() *NotificationPreferenceUpsert {
	u.SetNull(notificationpreference.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *NotificationPreferenceUpsert) SetUpdatedBy(v uint32) *NotificationPreferenceUpsert {
	u.Set(notificationpreference.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *NotificationPreferenceUpsert) UpdateUpdatedBy() *NotificationPreferenceUpsert {
	u.SetExcluded(notificationpreference.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *NotificationPreferenceUpsert) AddUpdatedBy(v uint32) *NotificationPreferenceUpsert {
	u.Add(notificationpreference.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *NotificationPreferenceUpsert) ClearUpdatedBy() *NotificationPreferenceUpsert {
	u.SetNull(notificationpreference.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *NotificationPreferenceUpsert) SetDeletedBy(v uint32) *NotificationPreferenceUpsert {
	u.Set(notificationpreference.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *NotificationPreferenceUpsert) UpdateDeletedBy() *NotificationPreferenceUpsert {
	u.SetExcluded(notificationpreference.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *NotificationPreferenceUpsert) AddDeletedBy(v uint32) *NotificationPreferenceUpsert {
	u.Add(notificationpreference.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *NotificationPreferenceUpsert) ClearDeletedBy() *NotificationPreferenceUpsert {
	u.SetNull(notificationpreference.FieldDeletedBy)
	return u
}

// SetUserID sets the "user_id" field.
func (u *NotificationPreferenceUpsert) SetUserID(v uint32) *NotificationPreferenceUpsert {
	u.Set(notificationpreference.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *NotificationPreferenceUpsert) UpdateUserID() *NotificationPreferenceUpsert {
	u.SetExcluded(notificationpreference.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *NotificationPreferenceUpsert) AddUserID(v uint32) *NotificationPreferenceUpsert {
	u.Add(notificationpreference.FieldUserID, v)
	return u
}

// SetQuietEnabled sets the "quiet_enabled" field.
func (u *NotificationPreferenceUpsert) SetQuietEnabled(v bool) *NotificationPreferenceUpsert {
	u.Set(notificationpreference.FieldQuietEnabled, v)
	return u
}

// UpdateQuietEnabled sets the "quiet_enabled" field to the value that was provided on create.
func (u *NotificationPreferenceUpsert) UpdateQuietEnabled() *NotificationPreferenceUpsert {
	u.SetExcluded(notificationpreference.FieldQuietEnabled)
	return u
}

// SetQuietStartMinute sets the "quiet_start_minute" field.
func (u *NotificationPreferenceUpsert) SetQuietStartMinute(v int32) *NotificationPreferenceUpsert {
	u.Set(notificationpreference.FieldQuietStartMinute, v)
	return u
}

// UpdateQuietStartMinute sets the "quiet_start_minute" field to the value that was provided on create.
func (u *NotificationPreferenceUpsert) UpdateQuietStartMinute() *NotificationPreferenceUpsert {
	u.SetExcluded(notificationpreference.FieldQuietStartMinute)
	return u
}

// AddQuietStartMinute adds v to the "quiet_start_minute" field.
func (u *NotificationPreferenceUpsert) AddQuietStartMinute(v int32) *NotificationPreferenceUpsert {
	u.Add(notificationpreference.FieldQuietStartMinute, v)
	return u
}

// SetQuietEndMinute sets the "quiet_end_minute" field.
func (u *NotificationPreferenceUpsert) SetQuietEndMinute(v int32) *NotificationPreferenceUpsert {
	u.Set(notificationpreference.FieldQuietEndMinute, v)
	return u
}

// UpdateQuietEndMinute sets the "quiet_end_minute" field to the value that was provided on create.
func (u *NotificationPreferenceUpsert) UpdateQuietEndMinute() *NotificationPreferenceUpsert {
	u.SetExcluded(notificationpreference.FieldQuietEndMinute)
	return u
}

// AddQuietEndMinute adds v to the "quiet_end_minute" field.
func (u *NotificationPreferenceUpsert) AddQuietEndMinute(v int32) *NotificationPreferenceUpsert {
	u.Add(notificationpreference.FieldQuietEndMinute, v)
	return u
}

// SetMutedCategoryIds sets the "muted_category_ids" field.
func (u *NotificationPreferenceUpsert) SetMutedCategoryIds(v []uint32) *NotificationPreferenceUpsert {
	u.Set(notificationpreference.FieldMutedCategoryIds, v)
	return u
}

// UpdateMutedCategoryIds sets the "muted_category_ids" field to the value that was provided on create.
func (u *NotificationPreferenceUpsert) UpdateMutedCategoryIds() *NotificationPreferenceUpsert {
	u.SetExcluded(notificationpreference.FieldMutedCategoryIds)
	return u
}

// ClearMutedCategoryIds clears the value of the "muted_category_ids" field.
func (u *NotificationPreferenceUpsert) ClearMutedCategoryIds() *NotificationPreferenceUpsert {
	u.SetNull(notificationpreference.FieldMutedCategoryIds)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NotificationPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationpreference.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationPreferenceUpsertOne) UpdateNewValues() *NotificationPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(notificationpreference.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(notificationpreference.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationPreference.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotificationPreferenceUpsertOne) Ignore() *NotificationPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationPreferenceUpsertOne) DoNothing() *NotificationPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationPreferenceCreate.OnConflict
// documentation for more info.
func (u *NotificationPreferenceUpsertOne) Update(set func(*NotificationPreferenceUpsert)) *NotificationPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationPreferenceUpsertOne) SetUpdatedAt(v time.Time) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertOne) UpdateUpdatedAt() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *NotificationPreferenceUpsertOne) ClearUpdatedAt() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *NotificationPreferenceUpsertOne) SetDeletedAt(v time.Time) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertOne) UpdateDeletedAt() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *NotificationPreferenceUpsertOne) ClearDeletedAt() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *NotificationPreferenceUpsertOne) SetCreatedBy(v uint32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *NotificationPreferenceUpsertOne) AddCreatedBy(v uint32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertOne) UpdateCreatedBy() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *NotificationPreferenceUpsertOne) ClearCreatedBy() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *NotificationPreferenceUpsertOne) SetUpdatedBy(v uint32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *NotificationPreferenceUpsertOne) AddUpdatedBy(v uint32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertOne) UpdateUpdatedBy() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *NotificationPreferenceUpsertOne) ClearUpdatedBy() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *NotificationPreferenceUpsertOne) SetDeletedBy(v uint32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *NotificationPreferenceUpsertOne) AddDeletedBy(v uint32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertOne) UpdateDeletedBy() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *NotificationPreferenceUpsertOne) ClearDeletedBy() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.ClearDeletedBy()
	})
}

// SetUserID sets the "user_id" field.
func (u *NotificationPreferenceUpsertOne) SetUserID(v uint32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *NotificationPreferenceUpsertOne) AddUserID(v uint32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertOne) UpdateUserID() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateUserID()
	})
}

// SetQuietEnabled sets the "quiet_enabled" field.
func (u *NotificationPreferenceUpsertOne) SetQuietEnabled(v bool) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetQuietEnabled(v)
	})
}

// UpdateQuietEnabled sets the "quiet_enabled" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertOne) UpdateQuietEnabled() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateQuietEnabled()
	})
}

// SetQuietStartMinute sets the "quiet_start_minute" field.
func (u *NotificationPreferenceUpsertOne) SetQuietStartMinute(v int32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetQuietStartMinute(v)
	})
}

// AddQuietStartMinute adds v to the "quiet_start_minute" field.
func (u *NotificationPreferenceUpsertOne) AddQuietStartMinute(v int32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.AddQuietStartMinute(v)
	})
}

// UpdateQuietStartMinute sets the "quiet_start_minute" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertOne) UpdateQuietStartMinute() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateQuietStartMinute()
	})
}

// SetQuietEndMinute sets the "quiet_end_minute" field.
func (u *NotificationPreferenceUpsertOne) SetQuietEndMinute(v int32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetQuietEndMinute(v)
	})
}

// AddQuietEndMinute adds v to the "quiet_end_minute" field.
func (u *NotificationPreferenceUpsertOne) AddQuietEndMinute(v int32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.AddQuietEndMinute(v)
	})
}

// UpdateQuietEndMinute sets the "quiet_end_minute" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertOne) UpdateQuietEndMinute() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateQuietEndMinute()
	})
}

// SetMutedCategoryIds sets the "muted_category_ids" field.
func (u *NotificationPreferenceUpsertOne) SetMutedCategoryIds(v []uint32) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetMutedCategoryIds(v)
	})
}

// UpdateMutedCategoryIds sets the "muted_category_ids" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertOne) UpdateMutedCategoryIds() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateMutedCategoryIds()
	})
}

// ClearMutedCategoryIds clears the value of the "muted_category_ids" field.
func (u *NotificationPreferenceUpsertOne) ClearMutedCategoryIds() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.ClearMutedCategoryIds()
	})
}

// Exec executes the query.
func (u *NotificationPreferenceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationPreferenceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationPreferenceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotificationPreferenceUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotificationPreferenceUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotificationPreferenceCreateBulk is the builder for creating many NotificationPreference entities in bulk.
type NotificationPreferenceCreateBulk struct {
	config
	err      error
	builders []*NotificationPreferenceCreate
	conflict []sql.ConflictOption
}

// Save creates the NotificationPreference entities in the database.
func (_c *NotificationPreferenceCreateBulk) Save(ctx context.Context) ([]*NotificationPreference, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationPreference, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationPreferenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationPreferenceCreateBulk) SaveX(ctx context.Context) []*NotificationPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationPreferenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationPreferenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationPreference.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationPreferenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationPreferenceCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotificationPreferenceUpsertBulk {
	_c.conflict = opts
	return &NotificationPreferenceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationPreferenceCreateBulk) OnConflictColumns(columns ...string) *NotificationPreferenceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationPreferenceUpsertBulk{
		create: _c,
	}
}

// NotificationPreferenceUpsertBulk is the builder for "upsert"-ing
// a bulk of NotificationPreference nodes.
type NotificationPreferenceUpsertBulk struct {
	create *NotificationPreferenceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotificationPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationpreference.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationPreferenceUpsertBulk) UpdateNewValues() *NotificationPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(notificationpreference.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(notificationpreference.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationPreference.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotificationPreferenceUpsertBulk) Ignore() *NotificationPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationPreferenceUpsertBulk) DoNothing() *NotificationPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationPreferenceCreateBulk.OnConflict
// documentation for more info.
func (u *NotificationPreferenceUpsertBulk) Update(set func(*NotificationPreferenceUpsert)) *NotificationPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationPreferenceUpsertBulk) SetUpdatedAt(v time.Time) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertBulk) UpdateUpdatedAt() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *NotificationPreferenceUpsertBulk) ClearUpdatedAt() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *NotificationPreferenceUpsertBulk) SetDeletedAt(v time.Time) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertBulk) UpdateDeletedAt() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *NotificationPreferenceUpsertBulk) ClearDeletedAt() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *NotificationPreferenceUpsertBulk) SetCreatedBy(v uint32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *NotificationPreferenceUpsertBulk) AddCreatedBy(v uint32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertBulk) UpdateCreatedBy() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *NotificationPreferenceUpsertBulk) ClearCreatedBy() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *NotificationPreferenceUpsertBulk) SetUpdatedBy(v uint32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *NotificationPreferenceUpsertBulk) AddUpdatedBy(v uint32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertBulk) UpdateUpdatedBy() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *NotificationPreferenceUpsertBulk) ClearUpdatedBy() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *NotificationPreferenceUpsertBulk) SetDeletedBy(v uint32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *NotificationPreferenceUpsertBulk) AddDeletedBy(v uint32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertBulk) UpdateDeletedBy() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *NotificationPreferenceUpsertBulk) ClearDeletedBy() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.ClearDeletedBy()
	})
}

// SetUserID sets the "user_id" field.
func (u *NotificationPreferenceUpsertBulk) SetUserID(v uint32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *NotificationPreferenceUpsertBulk) AddUserID(v uint32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertBulk) UpdateUserID() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateUserID()
	})
}

// SetQuietEnabled sets the "quiet_enabled" field.
func (u *NotificationPreferenceUpsertBulk) SetQuietEnabled(v bool) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetQuietEnabled(v)
	})
}

// UpdateQuietEnabled sets the "quiet_enabled" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertBulk) UpdateQuietEnabled() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateQuietEnabled()
	})
}

// SetQuietStartMinute sets the "quiet_start_minute" field.
func (u *NotificationPreferenceUpsertBulk) SetQuietStartMinute(v int32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetQuietStartMinute(v)
	})
}

// AddQuietStartMinute adds v to the "quiet_start_minute" field.
func (u *NotificationPreferenceUpsertBulk) AddQuietStartMinute(v int32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.AddQuietStartMinute(v)
	})
}

// UpdateQuietStartMinute sets the "quiet_start_minute" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertBulk) UpdateQuietStartMinute() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateQuietStartMinute()
	})
}

// SetQuietEndMinute sets the "quiet_end_minute" field.
func (u *NotificationPreferenceUpsertBulk) SetQuietEndMinute(v int32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetQuietEndMinute(v)
	})
}

// AddQuietEndMinute adds v to the "quiet_end_minute" field.
func (u *NotificationPreferenceUpsertBulk) AddQuietEndMinute(v int32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.AddQuietEndMinute(v)
	})
}

// UpdateQuietEndMinute sets the "quiet_end_minute" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertBulk) UpdateQuietEndMinute() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateQuietEndMinute()
	})
}

// SetMutedCategoryIds sets the "muted_category_ids" field.
func (u *NotificationPreferenceUpsertBulk) SetMutedCategoryIds(v []uint32) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetMutedCategoryIds(v)
	})
}

// UpdateMutedCategoryIds sets the "muted_category_ids" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertBulk) UpdateMutedCategoryIds() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateMutedCategoryIds()
	})
}

// ClearMutedCategoryIds clears the value of the "muted_category_ids" field.
func (u *NotificationPreferenceUpsertBulk) ClearMutedCategoryIds() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.ClearMutedCategoryIds()
	})
}

// Exec executes the query.
func (u *NotificationPreferenceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotificationPreferenceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationPreferenceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationPreferenceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
