// Code generated by ent, DO NOT EDIT.

package notificationtemplate

import (
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldDeletedBy, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldIsEnabled, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldRemark, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldName, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldCode, v))
}

// TitleTemplate applies equality check predicate on the "title_template" field. It's identical to TitleTemplateEQ.
func TitleTemplate(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldTitleTemplate, v))
}

// ContentTemplate applies equality check predicate on the "content_template" field. It's identical to ContentTemplateEQ.
func ContentTemplate(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldContentTemplate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldDeletedBy))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldIsEnabled, v))
}

// IsEnabledIsNil applies the IsNil predicate on the "is_enabled" field.
func IsEnabledIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldIsEnabled))
}

// IsEnabledNotNil applies the NotNil predicate on the "is_enabled" field.
func IsEnabledNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldIsEnabled))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContainsFold(FieldRemark, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContainsFold(FieldName, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasSuffix(FieldCode, v))
}

// CodeIsNil applies the IsNil predicate on the "code" field.
func CodeIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldCode))
}

// CodeNotNil applies the NotNil predicate on the "code" field.
func CodeNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldCode))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContainsFold(FieldCode, v))
}

// TitleTemplateEQ applies the EQ predicate on the "title_template" field.
func TitleTemplateEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldTitleTemplate, v))
}

// TitleTemplateNEQ applies the NEQ predicate on the "title_template" field.
func TitleTemplateNEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldTitleTemplate, v))
}

// TitleTemplateIn applies the In predicate on the "title_template" field.
func TitleTemplateIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldTitleTemplate, vs...))
}

// TitleTemplateNotIn applies the NotIn predicate on the "title_template" field.
func TitleTemplateNotIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldTitleTemplate, vs...))
}

// TitleTemplateGT applies the GT predicate on the "title_template" field.
func TitleTemplateGT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldTitleTemplate, v))
}

// TitleTemplateGTE applies the GTE predicate on the "title_template" field.
func TitleTemplateGTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldTitleTemplate, v))
}

// TitleTemplateLT applies the LT predicate on the "title_template" field.
func TitleTemplateLT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldTitleTemplate, v))
}

// TitleTemplateLTE applies the LTE predicate on the "title_template" field.
func TitleTemplateLTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldTitleTemplate, v))
}

// TitleTemplateContains applies the Contains predicate on the "title_template" field.
func TitleTemplateContains(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContains(FieldTitleTemplate, v))
}

// TitleTemplateHasPrefix applies the HasPrefix predicate on the "title_template" field.
func TitleTemplateHasPrefix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasPrefix(FieldTitleTemplate, v))
}

// TitleTemplateHasSuffix applies the HasSuffix predicate on the "title_template" field.
func TitleTemplateHasSuffix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasSuffix(FieldTitleTemplate, v))
}

// TitleTemplateIsNil applies the IsNil predicate on the "title_template" field.
func TitleTemplateIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldTitleTemplate))
}

// TitleTemplateNotNil applies the NotNil predicate on the "title_template" field.
func TitleTemplateNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldTitleTemplate))
}

// TitleTemplateEqualFold applies the EqualFold predicate on the "title_template" field.
func TitleTemplateEqualFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEqualFold(FieldTitleTemplate, v))
}

// TitleTemplateContainsFold applies the ContainsFold predicate on the "title_template" field.
func TitleTemplateContainsFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContainsFold(FieldTitleTemplate, v))
}

// ContentTemplateEQ applies the EQ predicate on the "content_template" field.
func ContentTemplateEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEQ(FieldContentTemplate, v))
}

// ContentTemplateNEQ applies the NEQ predicate on the "content_template" field.
func ContentTemplateNEQ(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNEQ(FieldContentTemplate, v))
}

// ContentTemplateIn applies the In predicate on the "content_template" field.
func ContentTemplateIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIn(FieldContentTemplate, vs...))
}

// ContentTemplateNotIn applies the NotIn predicate on the "content_template" field.
func ContentTemplateNotIn(vs ...string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotIn(FieldContentTemplate, vs...))
}

// ContentTemplateGT applies the GT predicate on the "content_template" field.
func ContentTemplateGT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGT(FieldContentTemplate, v))
}

// ContentTemplateGTE applies the GTE predicate on the "content_template" field.
func ContentTemplateGTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldGTE(FieldContentTemplate, v))
}

// ContentTemplateLT applies the LT predicate on the "content_template" field.
func ContentTemplateLT(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLT(FieldContentTemplate, v))
}

// ContentTemplateLTE applies the LTE predicate on the "content_template" field.
func ContentTemplateLTE(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldLTE(FieldContentTemplate, v))
}

// ContentTemplateContains applies the Contains predicate on the "content_template" field.
func ContentTemplateContains(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContains(FieldContentTemplate, v))
}

// ContentTemplateHasPrefix applies the HasPrefix predicate on the "content_template" field.
func ContentTemplateHasPrefix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasPrefix(FieldContentTemplate, v))
}

// ContentTemplateHasSuffix applies the HasSuffix predicate on the "content_template" field.
func ContentTemplateHasSuffix(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldHasSuffix(FieldContentTemplate, v))
}

// ContentTemplateIsNil applies the IsNil predicate on the "content_template" field.
func ContentTemplateIsNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldIsNull(FieldContentTemplate))
}

// ContentTemplateNotNil applies the NotNil predicate on the "content_template" field.
func ContentTemplateNotNil() predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldNotNull(FieldContentTemplate))
}

// ContentTemplateEqualFold applies the EqualFold predicate on the "content_template" field.
func ContentTemplateEqualFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldEqualFold(FieldContentTemplate, v))
}

// ContentTemplateContainsFold applies the ContainsFold predicate on the "content_template" field.
func ContentTemplateContainsFold(v string) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.FieldContainsFold(FieldContentTemplate, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationTemplate) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationTemplate) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationTemplate) predicate.NotificationTemplate {
	return predicate.NotificationTemplate(sql.NotPredicates(p))
}
