// Code generated by ent, DO NOT EDIT.

package aiusagelog

import (
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldTenantID, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldProviderID, v))
}

// ConversationID applies equality check predicate on the "conversation_id" field. It's identical to ConversationIDEQ.
func ConversationID(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldConversationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldUserID, v))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldModelName, v))
}

// PromptTokens applies equality check predicate on the "prompt_tokens" field. It's identical to PromptTokensEQ.
func PromptTokens(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldPromptTokens, v))
}

// CompletionTokens applies equality check predicate on the "completion_tokens" field. It's identical to CompletionTokensEQ.
func CompletionTokens(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldCompletionTokens, v))
}

// TotalTokens applies equality check predicate on the "total_tokens" field. It's identical to TotalTokensEQ.
func TotalTokens(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldTotalTokens, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldDurationMs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotNull(FieldCreatedAt))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotNull(FieldTenantID))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotIn(FieldProviderID, vs...))
}

// ProviderIDGT applies the GT predicate on the "provider_id" field.
func ProviderIDGT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGT(FieldProviderID, v))
}

// ProviderIDGTE applies the GTE predicate on the "provider_id" field.
func ProviderIDGTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGTE(FieldProviderID, v))
}

// ProviderIDLT applies the LT predicate on the "provider_id" field.
func ProviderIDLT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLT(FieldProviderID, v))
}

// ProviderIDLTE applies the LTE predicate on the "provider_id" field.
func ProviderIDLTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLTE(FieldProviderID, v))
}

// ProviderIDIsNil applies the IsNil predicate on the "provider_id" field.
func ProviderIDIsNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIsNull(FieldProviderID))
}

// ProviderIDNotNil applies the NotNil predicate on the "provider_id" field.
func ProviderIDNotNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotNull(FieldProviderID))
}

// ConversationIDEQ applies the EQ predicate on the "conversation_id" field.
func ConversationIDEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldConversationID, v))
}

// ConversationIDNEQ applies the NEQ predicate on the "conversation_id" field.
func ConversationIDNEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNEQ(FieldConversationID, v))
}

// ConversationIDIn applies the In predicate on the "conversation_id" field.
func ConversationIDIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIn(FieldConversationID, vs...))
}

// ConversationIDNotIn applies the NotIn predicate on the "conversation_id" field.
func ConversationIDNotIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotIn(FieldConversationID, vs...))
}

// ConversationIDGT applies the GT predicate on the "conversation_id" field.
func ConversationIDGT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGT(FieldConversationID, v))
}

// ConversationIDGTE applies the GTE predicate on the "conversation_id" field.
func ConversationIDGTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGTE(FieldConversationID, v))
}

// ConversationIDLT applies the LT predicate on the "conversation_id" field.
func ConversationIDLT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLT(FieldConversationID, v))
}

// ConversationIDLTE applies the LTE predicate on the "conversation_id" field.
func ConversationIDLTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLTE(FieldConversationID, v))
}

// ConversationIDIsNil applies the IsNil predicate on the "conversation_id" field.
func ConversationIDIsNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIsNull(FieldConversationID))
}

// ConversationIDNotNil applies the NotNil predicate on the "conversation_id" field.
func ConversationIDNotNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotNull(FieldConversationID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotNull(FieldUserID))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameIsNil applies the IsNil predicate on the "model_name" field.
func ModelNameIsNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIsNull(FieldModelName))
}

// ModelNameNotNil applies the NotNil predicate on the "model_name" field.
func ModelNameNotNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotNull(FieldModelName))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldContainsFold(FieldModelName, v))
}

// PromptTokensEQ applies the EQ predicate on the "prompt_tokens" field.
func PromptTokensEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldPromptTokens, v))
}

// PromptTokensNEQ applies the NEQ predicate on the "prompt_tokens" field.
func PromptTokensNEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNEQ(FieldPromptTokens, v))
}

// PromptTokensIn applies the In predicate on the "prompt_tokens" field.
func PromptTokensIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIn(FieldPromptTokens, vs...))
}

// PromptTokensNotIn applies the NotIn predicate on the "prompt_tokens" field.
func PromptTokensNotIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotIn(FieldPromptTokens, vs...))
}

// PromptTokensGT applies the GT predicate on the "prompt_tokens" field.
func PromptTokensGT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGT(FieldPromptTokens, v))
}

// PromptTokensGTE applies the GTE predicate on the "prompt_tokens" field.
func PromptTokensGTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGTE(FieldPromptTokens, v))
}

// PromptTokensLT applies the LT predicate on the "prompt_tokens" field.
func PromptTokensLT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLT(FieldPromptTokens, v))
}

// PromptTokensLTE applies the LTE predicate on the "prompt_tokens" field.
func PromptTokensLTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLTE(FieldPromptTokens, v))
}

// PromptTokensIsNil applies the IsNil predicate on the "prompt_tokens" field.
func PromptTokensIsNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIsNull(FieldPromptTokens))
}

// PromptTokensNotNil applies the NotNil predicate on the "prompt_tokens" field.
func PromptTokensNotNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotNull(FieldPromptTokens))
}

// CompletionTokensEQ applies the EQ predicate on the "completion_tokens" field.
func CompletionTokensEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldCompletionTokens, v))
}

// CompletionTokensNEQ applies the NEQ predicate on the "completion_tokens" field.
func CompletionTokensNEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNEQ(FieldCompletionTokens, v))
}

// CompletionTokensIn applies the In predicate on the "completion_tokens" field.
func CompletionTokensIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIn(FieldCompletionTokens, vs...))
}

// CompletionTokensNotIn applies the NotIn predicate on the "completion_tokens" field.
func CompletionTokensNotIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotIn(FieldCompletionTokens, vs...))
}

// CompletionTokensGT applies the GT predicate on the "completion_tokens" field.
func CompletionTokensGT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGT(FieldCompletionTokens, v))
}

// CompletionTokensGTE applies the GTE predicate on the "completion_tokens" field.
func CompletionTokensGTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGTE(FieldCompletionTokens, v))
}

// CompletionTokensLT applies the LT predicate on the "completion_tokens" field.
func CompletionTokensLT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLT(FieldCompletionTokens, v))
}

// CompletionTokensLTE applies the LTE predicate on the "completion_tokens" field.
func CompletionTokensLTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLTE(FieldCompletionTokens, v))
}

// CompletionTokensIsNil applies the IsNil predicate on the "completion_tokens" field.
func CompletionTokensIsNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIsNull(FieldCompletionTokens))
}

// CompletionTokensNotNil applies the NotNil predicate on the "completion_tokens" field.
func CompletionTokensNotNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotNull(FieldCompletionTokens))
}

// TotalTokensEQ applies the EQ predicate on the "total_tokens" field.
func TotalTokensEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalTokensNEQ applies the NEQ predicate on the "total_tokens" field.
func TotalTokensNEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNEQ(FieldTotalTokens, v))
}

// TotalTokensIn applies the In predicate on the "total_tokens" field.
func TotalTokensIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIn(FieldTotalTokens, vs...))
}

// TotalTokensNotIn applies the NotIn predicate on the "total_tokens" field.
func TotalTokensNotIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotIn(FieldTotalTokens, vs...))
}

// TotalTokensGT applies the GT predicate on the "total_tokens" field.
func TotalTokensGT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGT(FieldTotalTokens, v))
}

// TotalTokensGTE applies the GTE predicate on the "total_tokens" field.
func TotalTokensGTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGTE(FieldTotalTokens, v))
}

// TotalTokensLT applies the LT predicate on the "total_tokens" field.
func TotalTokensLT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLT(FieldTotalTokens, v))
}

// TotalTokensLTE applies the LTE predicate on the "total_tokens" field.
func TotalTokensLTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLTE(FieldTotalTokens, v))
}

// TotalTokensIsNil applies the IsNil predicate on the "total_tokens" field.
func TotalTokensIsNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIsNull(FieldTotalTokens))
}

// TotalTokensNotNil applies the NotNil predicate on the "total_tokens" field.
func TotalTokensNotNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotNull(FieldTotalTokens))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v uint32) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.FieldNotNull(FieldDurationMs))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AiUsageLog) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AiUsageLog) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AiUsageLog) predicate.AiUsageLog {
	return predicate.AiUsageLog(sql.NotPredicates(p))
}
