// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type Api struct {
	Id                int64  `json:"id,optional"`
	Operation         string `json:"operation,optional"`
	Path              string `json:"path,optional"`
	Method            string `json:"method,optional"`
	Module            string `json:"module,optional"`
	ModuleDescription string `json:"moduleDescription,optional"`
	BusinessModule    string `json:"businessModule,optional"`
	Description       string `json:"description,optional"`
	Scope             string `json:"scope,optional"`
	Status            string `json:"status,optional"`
	CreatedBy         int64  `json:"createdBy,optional"`
	UpdatedBy         int64  `json:"updatedBy,optional"`
	DeletedBy         int64  `json:"deletedBy,optional"`
	CreatedAt         string `json:"createdAt,optional"`
	UpdatedAt         string `json:"updatedAt,optional"`
	DeletedAt         string `json:"deletedAt,optional"`
}

type ApiDeleteReq struct {
	Id int64 `path:"id,optional"`
}

type ApiGetReq struct {
	Id       int64  `path:"id,optional"`
	ViewMask string `form:"viewMask,optional"`
}

type CreateApiRequest struct {
	Data Api `json:"data,optional"`
}

type ListApiResponse struct {
	Items []Api  `json:"items,optional"`
	Total string `json:"total,optional"`
}

type UpdateApiRequest struct {
	Id           int64  `path:"id,optional"`
	Data         Api    `json:"data,optional"`
	UpdateMask   string `json:"updateMask,optional"`
	AllowMissing bool   `json:"allowMissing,optional"`
}
