// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type ApiAuditLog struct {
	Id             int64       `json:"id,optional"`
	TenantId       int64       `json:"tenantId,optional"`
	TenantName     string      `json:"tenantName,optional"`
	UserId         int64       `json:"userId,optional"`
	Username       string      `json:"username,optional"`
	IpAddress      string      `json:"ipAddress,optional"`
	GeoLocation    GeoLocation `json:"geoLocation,optional"`
	DeviceInfo     DeviceInfo  `json:"deviceInfo,optional"`
	Referer        string      `json:"referer,optional"`
	AppVersion     string      `json:"appVersion,optional"`
	HttpMethod     string      `json:"httpMethod,optional"`
	Path           string      `json:"path,optional"`
	RequestUri     string      `json:"requestUri,optional"`
	ApiModule      string      `json:"apiModule,optional"`
	ApiOperation   string      `json:"apiOperation,optional"`
	ApiDescription string      `json:"apiDescription,optional"`
	RequestId      string      `json:"requestId,optional"`
	TraceId        string      `json:"traceId,optional"`
	SpanId         string      `json:"spanId,optional"`
	LatencyMs      int64       `json:"latencyMs,optional"`
	Success        bool        `json:"success,optional"`
	StatusCode     int64       `json:"statusCode,optional"`
	Reason         string      `json:"reason,optional"`
	RequestHeader  string      `json:"requestHeader,optional"`
	RequestBody    string      `json:"requestBody,optional"`
	Response       string      `json:"response,optional"`
	LogHash        string      `json:"logHash,optional"`
	Signature      string      `json:"signature,optional"`
	CreatedAt      string      `json:"createdAt,optional"`
}

type ApiAuditLogGetReq struct {
	Id       int64  `path:"id,optional"`
	ViewMask string `form:"viewMask,optional"`
}

type ListApiAuditLogResponse struct {
	Items []ApiAuditLog `json:"items,optional"`
	Total string        `json:"total,optional"`
}
