// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type DataAccessAuditLog struct {
	Id              int64  `json:"id,optional"`
	TenantId        int64  `json:"tenantId,optional"`
	TenantName      string `json:"tenantName,optional"`
	UserId          int64  `json:"userId,optional"`
	Username        string `json:"username,optional"`
	IpAddress       string `json:"ipAddress,optional"`
	RequestId       string `json:"requestId,optional"`
	DataSource      string `json:"dataSource,optional"`
	TableName       string `json:"tableName,optional"`
	DataId          string `json:"dataId,optional"`
	AccessType      string `json:"accessType,optional"`
	SqlDigest       string `json:"sqlDigest,optional"`
	SqlText         string `json:"sqlText,optional"`
	AffectedRows    int64  `json:"affectedRows,optional"`
	LatencyMs       int64  `json:"latencyMs,optional"`
	Success         bool   `json:"success,optional"`
	SensitiveLevel  string `json:"sensitiveLevel,optional"`
	DataMasked      bool   `json:"dataMasked,optional"`
	MaskingRules    string `json:"maskingRules,optional"`
	BusinessPurpose string `json:"businessPurpose,optional"`
	DataCategory    string `json:"dataCategory,optional"`
	DbUser          string `json:"dbUser,optional"`
	LogHash         string `json:"logHash,optional"`
	Signature       string `json:"signature,optional"`
	CreatedAt       string `json:"createdAt,optional"`
}

type DataAccessAuditLogGetReq struct {
	Id       int64  `path:"id,optional"`
	ViewMask string `form:"viewMask,optional"`
}

type ListDataAccessAuditLogResponse struct {
	Items []DataAccessAuditLog `json:"items,optional"`
	Total string               `json:"total,optional"`
}
