// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateOrgUnitRequest struct {
	Data OrgUnit `json:"data,optional"`
}

type ListOrgUnitResponse struct {
	Items []OrgUnit `json:"items,optional"`
	Total string    `json:"total,optional"`
}

type OrgUnit struct {
	Id                 int64                  `json:"id,optional"`
	Name               string                 `json:"name,optional"`
	Code               string                 `json:"code,optional"`
	Type               string                 `json:"type,optional"`
	Path               string                 `json:"path,optional"`
	Status             string                 `json:"status,optional"`
	SortOrder          int64                  `json:"sortOrder,optional"`
	LeaderId           int64                  `json:"leaderId,optional"`
	LeaderName         string                 `json:"leaderName,optional"`
	TenantId           int64                  `json:"tenantId,optional"`
	TenantName         string                 `json:"tenantName,optional"`
	Remark             string                 `json:"remark,optional"`
	Description        string                 `json:"description,optional"`
	BusinessScopes     []string               `json:"businessScopes,optional"`
	ExternalId         string                 `json:"externalId,optional"`
	IsLegalEntity      bool                   `json:"isLegalEntity,optional"`
	RegistrationNumber string                 `json:"registrationNumber,optional"`
	TaxId              string                 `json:"taxId,optional"`
	LegalEntityOrgId   int64                  `json:"legalEntityOrgId,optional"`
	Address            string                 `json:"address,optional"`
	Phone              string                 `json:"phone,optional"`
	Email              string                 `json:"email,optional"`
	Timezone           string                 `json:"timezone,optional"`
	Country            string                 `json:"country,optional"`
	Latitude           float64                `json:"latitude,optional"`
	Longitude          float64                `json:"longitude,optional"`
	StartAt            string                 `json:"startAt,optional"`
	EndAt              string                 `json:"endAt,optional"`
	Attributes         map[string]interface{} `json:"attributes,optional"`
	PermissionTags     []string               `json:"permissionTags,optional"`
	ContactUserId      int64                  `json:"contactUserId,optional"`
	ContactUserName    string                 `json:"contactUserName,optional"`
	ParentId           int64                  `json:"parentId,optional"`
	Children           []OrgUnit              `json:"children,optional"`
	CreatedBy          int64                  `json:"createdBy,optional"`
	UpdatedBy          int64                  `json:"updatedBy,optional"`
	DeletedBy          int64                  `json:"deletedBy,optional"`
	CreatedAt          string                 `json:"createdAt,optional"`
	UpdatedAt          string                 `json:"updatedAt,optional"`
	DeletedAt          string                 `json:"deletedAt,optional"`
}

type OrgUnitDeleteReq struct {
	Id int64 `path:"id,optional"`
}

type OrgUnitGetReq struct {
	Id       int64  `path:"id,optional"`
	ViewMask string `form:"viewMask,optional"`
}

type UpdateOrgUnitRequest struct {
	Id           int64   `path:"id,optional"`
	Data         OrgUnit `json:"data,optional"`
	UpdateMask   string  `json:"updateMask,optional"`
	AllowMissing bool    `json:"allowMissing,optional"`
}
