// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreatePermissionGroupRequest struct {
	Data PermissionGroup `json:"data,optional"`
}

type ListPermissionGroupResponse struct {
	Items []PermissionGroup `json:"items,optional"`
	Total int64            `json:"total,optional"`
}

type PermissionGroup struct {
	Id          int64             `json:"id,optional"`
	Name        string            `json:"name,optional"`
	Path        string            `json:"path,optional"`
	Module      string            `json:"module,optional"`
	SortOrder   int64             `json:"sortOrder,optional"`
	Status      string            `json:"status,optional"`
	Description string            `json:"description,optional"`
	ParentId    int64             `json:"parentId,optional"`
	Children    []PermissionGroup `json:"children,optional"`
	CreatedBy   int64             `json:"createdBy,optional"`
	UpdatedBy   int64             `json:"updatedBy,optional"`
	DeletedBy   int64             `json:"deletedBy,optional"`
	CreatedAt   string            `json:"createdAt,optional"`
	UpdatedAt   string            `json:"updatedAt,optional"`
	DeletedAt   string            `json:"deletedAt,optional"`
}

type PermissionGroupDeleteReq struct {
	Id int64 `path:"id,optional"`
}

type PermissionGroupGetReq struct {
	Id       int64  `path:"id,optional"`
	ViewMask string `form:"viewMask,optional"`
}

type UpdatePermissionGroupRequest struct {
	Id           int64           `path:"id,optional"`
	Data         PermissionGroup `json:"data,optional"`
	UpdateMask   string          `json:"updateMask,optional"`
	AllowMissing bool            `json:"allowMissing,optional"`
}
