// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreatePlanModuleRequest struct {
	Data PlanModule `json:"data,optional"`
}

type ListPlanModuleResponse struct {
	Items []PlanModule `json:"items,optional"`
	Total string       `json:"total,optional"`
}

type PlanModule struct {
	Id        int64  `json:"id,optional"`
	PlanId    int64  `json:"planId,optional"`
	Module    string `json:"module,optional"`
	CreatedBy int64  `json:"createdBy,optional"`
	UpdatedBy int64  `json:"updatedBy,optional"`
	DeletedBy int64  `json:"deletedBy,optional"`
	CreatedAt string `json:"createdAt,optional"`
	UpdatedAt string `json:"updatedAt,optional"`
	DeletedAt string `json:"deletedAt,optional"`
}

type PlanModuleDeleteReq struct {
	Id int64 `form:"id,optional"`
}

type PlanModuleGetReq struct {
	Id       int64  `path:"id,optional"`
	ViewMask string `form:"viewMask,optional"`
}

type UpdatePlanModuleRequest struct {
	Id           int64      `path:"id,optional"`
	Data         PlanModule `json:"data,optional"`
	UpdateMask   string     `json:"updateMask,optional"`
	AllowMissing bool       `json:"allowMissing,optional"`
}
