// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreatePlanRequest struct {
	Data Plan `json:"data,optional"`
}

type ListPlanResponse struct {
	Items []Plan `json:"items,optional"`
	Total string `json:"total,optional"`
}

type Plan struct {
	Id                int64  `json:"id,optional"`
	Name              string `json:"name,optional"`
	Version           string `json:"version,optional"`
	ExpiryPolicy      string `json:"expiryPolicy,optional"`
	DataRetentionDays int64  `json:"dataRetentionDays,optional"`
	Description       string `json:"description,optional"`
	Remark            string `json:"remark,optional"`
	CreatedBy         int64  `json:"createdBy,optional"`
	UpdatedBy         int64  `json:"updatedBy,optional"`
	DeletedBy         int64  `json:"deletedBy,optional"`
	CreatedAt         string `json:"createdAt,optional"`
	UpdatedAt         string `json:"updatedAt,optional"`
	DeletedAt         string `json:"deletedAt,optional"`
}

type PlanDeleteReq struct {
	Id int64 `form:"id,optional"`
}

type PlanGetReq struct {
	Id       int64  `path:"id,optional"`
	ViewMask string `form:"viewMask,optional"`
}

type UpdatePlanRequest struct {
	Id           int64  `path:"id,optional"`
	Data         Plan   `json:"data,optional"`
	UpdateMask   string `json:"updateMask,optional"`
	AllowMissing bool   `json:"allowMissing,optional"`
}
