// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type RedisCacheMonitorInfo struct {
	Sections []InfoSection  `json:"sections,optional"`
	DbSize   string         `json:"dbSize,optional"`
	Slowlog  []SlowLogEntry `json:"slowlog,optional"`
}
