// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type ControlTaskRequest struct {
	ControlType string `json:"controlType,optional"`
	TypeName    string `json:"typeName,optional"`
}

type CreateTaskRequest struct {
	Data Task `json:"data,optional"`
}

type ListTaskResponse struct {
	Items []Task `json:"items,optional"`
	Total int64 `json:"total,optional"`
}

type ListTaskTypeNameResponse struct {
	TypeNames []string `json:"typeNames,optional"`
}

type RestartAllTaskResponse struct {
	Count int64 `json:"count,optional"`
}

type Task struct {
	Id          int64      `json:"id,optional"`
	Type        string     `json:"type,optional"`
	TypeName    string     `json:"typeName,optional"`
	TaskPayload string     `json:"taskPayload,optional"`
	CronSpec    string     `json:"cronSpec,optional"`
	TaskOptions TaskOption `json:"taskOptions,optional"`
	Enable      bool       `json:"enable,optional"`
	Remark      string     `json:"remark,optional"`
	TenantId    int64      `json:"tenantId,optional"`
	CreatedBy   int64      `json:"createdBy,optional"`
	UpdatedBy   int64      `json:"updatedBy,optional"`
	DeletedBy   int64      `json:"deletedBy,optional"`
	CreatedAt   string     `json:"createdAt,optional"`
	UpdatedAt   string     `json:"updatedAt,optional"`
	DeletedAt   string     `json:"deletedAt,optional"`
}

type TaskDeleteReq struct {
	Id int64 `path:"id,optional"`
}

type TaskGetByIdReq struct {
	Id       int64  `path:"id,optional"`
	TypeName string `form:"typeName,optional"`
	ViewMask string `form:"viewMask,optional"`
}

type TaskGetByTypeNameReq struct {
	TypeName string `path:"typeName,optional"`
	Id       int64  `form:"id,optional"`
	ViewMask string `form:"viewMask,optional"`
}

type UpdateTaskRequest struct {
	Id           int64  `path:"id,optional"`
	Data         Task   `json:"data,optional"`
	UpdateMask   string `json:"updateMask,optional"`
	AllowMissing bool   `json:"allowMissing,optional"`
}
