// Code generated by ent, DO NOT EDIT.

package monitoralertrule

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the monitoralertrule type in the database.
	Label = "monitor_alert_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldMetric holds the string denoting the metric field in the database.
	FieldMetric = "metric"
	// FieldOp holds the string denoting the op field in the database.
	FieldOp = "op"
	// FieldThreshold holds the string denoting the threshold field in the database.
	FieldThreshold = "threshold"
	// FieldCooldownMinutes holds the string denoting the cooldown_minutes field in the database.
	FieldCooldownMinutes = "cooldown_minutes"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldIsEnabled holds the string denoting the is_enabled field in the database.
	FieldIsEnabled = "is_enabled"
	// FieldLastFiring holds the string denoting the last_firing field in the database.
	FieldLastFiring = "last_firing"
	// FieldLastValue holds the string denoting the last_value field in the database.
	FieldLastValue = "last_value"
	// FieldLastAlertedAt holds the string denoting the last_alerted_at field in the database.
	FieldLastAlertedAt = "last_alerted_at"
	// Table holds the table name of the monitoralertrule in the database.
	Table = "monitor_alert_rules"
)

// Columns holds all SQL columns for monitoralertrule fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldRemark,
	FieldName,
	FieldMetric,
	FieldOp,
	FieldThreshold,
	FieldCooldownMinutes,
	FieldChannel,
	FieldTarget,
	FieldIsEnabled,
	FieldLastFiring,
	FieldLastValue,
	FieldLastAlertedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCooldownMinutes holds the default value on creation for the "cooldown_minutes" field.
	DefaultCooldownMinutes uint32
	// TargetValidator is a validator for the "target" field. It is called by the builders before save.
	TargetValidator func(string) error
	// DefaultIsEnabled holds the default value on creation for the "is_enabled" field.
	DefaultIsEnabled bool
	// DefaultLastFiring holds the default value on creation for the "last_firing" field.
	DefaultLastFiring bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// Metric defines the type for the "metric" enum field.
type Metric string

// Metric values.
const (
	MetricGoGoroutines      Metric = "GO_GOROUTINES"
	MetricGoMemAllocMb      Metric = "GO_MEM_ALLOC_MB"
	MetricDbOpenConnections Metric = "DB_OPEN_CONNECTIONS"
	MetricDbPingFail        Metric = "DB_PING_FAIL"
	MetricRedisDbSize       Metric = "REDIS_DB_SIZE"
)

func (m Metric) String() string {
	return string(m)
}

// MetricValidator is a validator for the "metric" field enum values. It is called by the builders before save.
func MetricValidator(m Metric) error {
	switch m {
	case MetricGoGoroutines, MetricGoMemAllocMb, MetricDbOpenConnections, MetricDbPingFail, MetricRedisDbSize:
		return nil
	default:
		return fmt.Errorf("monitoralertrule: invalid enum value for metric field: %q", m)
	}
}

// Op defines the type for the "op" enum field.
type Op string

// Op values.
const (
	OpGe Op = "GE"
	OpLe Op = "LE"
)

func (_op Op) String() string {
	return string(_op)
}

// OpValidator is a validator for the "op" field enum values. It is called by the builders before save.
func OpValidator(_op Op) error {
	switch _op {
	case OpGe, OpLe:
		return nil
	default:
		return fmt.Errorf("monitoralertrule: invalid enum value for op field: %q", _op)
	}
}

// Channel defines the type for the "channel" enum field.
type Channel string

// Channel values.
const (
	ChannelEmail   Channel = "EMAIL"
	ChannelWebhook Channel = "WEBHOOK"
)

func (c Channel) String() string {
	return string(c)
}

// ChannelValidator is a validator for the "channel" field enum values. It is called by the builders before save.
func ChannelValidator(c Channel) error {
	switch c {
	case ChannelEmail, ChannelWebhook:
		return nil
	default:
		return fmt.Errorf("monitoralertrule: invalid enum value for channel field: %q", c)
	}
}

// OrderOption defines the ordering options for the MonitorAlertRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByMetric orders the results by the metric field.
func ByMetric(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetric, opts...).ToFunc()
}

// ByOp orders the results by the op field.
func ByOp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOp, opts...).ToFunc()
}

// ByThreshold orders the results by the threshold field.
func ByThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThreshold, opts...).ToFunc()
}

// ByCooldownMinutes orders the results by the cooldown_minutes field.
func ByCooldownMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldownMinutes, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByIsEnabled orders the results by the is_enabled field.
func ByIsEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEnabled, opts...).ToFunc()
}

// ByLastFiring orders the results by the last_firing field.
func ByLastFiring(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastFiring, opts...).ToFunc()
}

// ByLastValue orders the results by the last_value field.
func ByLastValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastValue, opts...).ToFunc()
}

// ByLastAlertedAt orders the results by the last_alerted_at field.
func ByLastAlertedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastAlertedAt, opts...).ToFunc()
}
